project_id = "qfklkkzxemsbeniyugiz"

[functions.weather]
verify_jwt = true

[functions.ai-agriculture-chat]
verify_jwt = true

[functions.google-maps-config]
verify_jwt = false

[functions.get-white-label-config]
verify_jwt = false

[functions.filter-community-image]
verify_jwt = true