import type { BaselineTask } from "../generator/baseline-generator.ts";
import type { AgronomicEvidencePack } from "./evidence-pack.ts";
import { HARNESS_VERSION, type HarnessExecution, type PlanIntent, type ScheduleHarnessContext } from "./types.ts";
import { buildCandidateGraph, canonicalSequence } from "./candidate-graph.ts";
import { requestPlan } from "./llm-v3.ts";
import { validatePlanIntent } from "./validator.ts";
const fallback=(c:ScheduleHarnessContext):PlanIntent=>({schema_version:"schedule_plan_intent_v3",status:"READY",sequence:canonicalSequence(c.graph).map((candidate_id,i)=>({candidate_id,sequence_order:i+1,status:"SCHEDULED" as const})),uncertainties:c.gaps,reasoning_summary:"Deterministic fallback preserved the required database-backed baseline; optional evidence candidates were not auto-applied."});
const materialize=(tasks:BaselineTask[],evidence:AgronomicEvidencePack,plan:PlanIntent):BaselineTask[]=>{const bm=new Map(tasks.map((t,i)=>[`task_${String(i+1).padStart(4,"0")}`,t]));const em=new Map(evidence.candidates.map(c=>[c.id,c.task]));return[...plan.sequence].filter(x=>x.status==="SCHEDULED"||x.status==="CONDITIONAL").sort((a,b)=>a.sequence_order-b.sequence_order).map(x=>bm.get(x.candidate_id)??em.get(x.candidate_id)).filter((t):t is BaselineTask=>Boolean(t));};
export async function applyScheduleHarness(tasks:BaselineTask[],input:{cropCode:string;cultivationMethod:string|null;cropCycle:string|null;gaps:string[];evidencePack:AgronomicEvidencePack}):Promise<HarnessExecution>{const graph=buildCandidateGraph(tasks,input.evidencePack.candidates);const context:ScheduleHarnessContext={cropCode:input.cropCode,cultivationMethod:input.cultivationMethod,cropCycle:input.cropCycle,gaps:[...input.gaps,...input.evidencePack.gaps],graph,evidencePack:input.evidencePack};let errors:string[]=[],provider:string|null=null,model:string|null=null;for(let attempt=1;attempt<=2;attempt++){try{const r=await requestPlan(context,errors);provider=r.provider;model=r.model;const e=validatePlanIntent(r.plan,graph);if(!e.length&&r.plan.status==="READY"){const materialized=materialize(tasks,input.evidencePack,r.plan);return{tasks:materialized,result:{applied:true,status:"READY",plan:r.plan,selectedIds:r.plan.sequence.filter(x=>x.status==="SCHEDULED"||x.status==="CONDITIONAL").map(x=>x.candidate_id),trace:{harness_version:HARNESS_VERSION,planner:"llm_evidence_pack",provider,model,attempts:attempt,baseline_candidate_count:tasks.length,evidence_candidate_count:input.evidencePack.candidates.length,materialized_candidate_count:materialized.length,domain_summary:input.evidencePack.domain_summary,validation_errors:[]}}};}errors=e.length?e:[`planner_status:${r.plan.status}`]}catch(error){errors=[error instanceof Error?error.message:String(error)];if(errors[0]==="MODEL_UNAVAILABLE")break;}}const plan=fallback(context);return{tasks:materialize(tasks,input.evidencePack,plan),result:{applied:true,status:"READY",plan,selectedIds:plan.sequence.map(x=>x.candidate_id),trace:{harness_version:HARNESS_VERSION,planner:"deterministic_fallback",provider,model,attempts:2,baseline_candidate_count:tasks.length,evidence_candidate_count:input.evidencePack.candidates.length,validation_errors:errors}}};}
