import type { BaselineTask } from "../generator/baseline-generator.ts";
import { HARNESS_VERSION, type HarnessResult, type PlanIntent } from "./types.ts";
import { validatePlanIntent } from "./validator.ts";

function candidateTasks(tasks: BaselineTask[]) {
  return tasks.map((t,index)=>({ index, task_type:t.task_type, stage_uuid:t.stage_uuid, stage_key:t.stage_key, rule_ids:[...t.rule_ids] }));
}
function deterministicPlan(tasks: BaselineTask[]): PlanIntent {
  const indices=tasks.map((_,index)=>index);
  return { schema_version:"schedule_plan_intent_v1", status:"READY", selected_candidate_indices:indices, sequence:indices.map((candidate_index,sequence_order)=>({candidate_index,sequence_order:sequence_order+1})), omissions:[], uncertainties:[], reasoning_summary:"Deterministic DB-SSOT baseline candidate set preserved; no agronomic values generated by the model." };
}
export async function applyScheduleHarness(tasks: BaselineTask[], context:{cropCode:string; cultivationMethod:string|null; cropCycle:string|null; gaps:string[]}): Promise<{tasks:BaselineTask[]; result:HarnessResult}> {
  const candidates=candidateTasks(tasks);
  // V1 is intentionally fail-closed and deterministic until a provider-backed planner is explicitly enabled.
  // This creates the validated PlanIntent seam without allowing any model to invent agronomy.
  const plan=deterministicPlan(tasks);
  const errors=validatePlanIntent(plan,candidates);
  if(errors.length) return { tasks, result:{applied:false,status:"INVALID_PLAN",plan:null,selectedIndices:[],trace:{harness_version:HARNESS_VERSION,validation_errors:errors}} };
  const selected=new Set(plan.sequence.map(x=>x.candidate_index));
  const ordered=plan.sequence.map(x=>tasks[x.candidate_index]).filter(Boolean);
  return { tasks: ordered.length===selected.size ? ordered : tasks, result:{applied:true,status:"READY",plan,selectedIndices:[...selected],trace:{harness_version:HARNESS_VERSION,planner:"deterministic_candidate_selector",candidate_count:candidates.length,validation_errors:[]}} };
}
