// PHASE-18: CANONICAL OBSERVATION ONTOLOGY (DATABASE-ALIGNED)

export const OBSERVATION_ONTOLOGY_VERSION = '2.0.0'; // Phase-18: Canonical DB-aligned

// CANONICAL ENGLISH OBSERVABLE KEYS
export enum ObservationKey {
  // A. ESTABLISHMENT & GERMINATION (0–30 DAS)
  SEED_NOT_GERMINATED = 'SEED_NOT_GERMINATED',
  POOR_GERMINATION_PERCENT = 'POOR_GERMINATION_PERCENT',
  GAPS_IN_FIELD = 'GAPS_IN_FIELD',
  SEEDLING_DIED = 'SEEDLING_DIED',
  SEEDLING_WILTED = 'SEEDLING_WILTED',
  SETT_EASILY_PULLED_OUT = 'SETT_EASILY_PULLED_OUT',
  ROOTS_SOFT_OR_BLACK = 'ROOTS_SOFT_OR_BLACK',
  ROOTS_ROTTED = 'ROOTS_ROTTED',
  SEED_DECAYED = 'SEED_DECAYED',
  SEEDLING_YELLOW = 'SEEDLING_YELLOW',
  SEEDLING_STUNTED = 'SEEDLING_STUNTED',
  PATCHY_EMERGENCE = 'PATCHY_EMERGENCE',
  IRREGULAR_PLANT_STAND = 'IRREGULAR_PLANT_STAND',
  SOIL_CRUSTING_VISIBLE = 'SOIL_CRUSTING_VISIBLE',
  WATER_LOGGING_AT_BASE = 'WATER_LOGGING_AT_BASE',
  DRY_SOIL_AT_GERMINATION = 'DRY_SOIL_AT_GERMINATION',
  
  // Failure Classes
  ESTABLISHMENT_FAILURE = 'ESTABLISHMENT_FAILURE',
  SOIL_BORNE_DISEASE = 'SOIL_BORNE_DISEASE',
  MOISTURE_STRESS = 'MOISTURE_STRESS',
  
  // B. VEGETATIVE GROWTH (Tillering / Branching / Grand Growth)
  SLOW_GROWTH = 'SLOW_GROWTH',
  STUNTED_PLANTS = 'STUNTED_PLANTS',
  SHORT_INTERNODES = 'SHORT_INTERNODES',
  EXCESSIVE_TILLERS = 'EXCESSIVE_TILLERS',
  POOR_TILLERING = 'POOR_TILLERING',
  WEAK_SHOOTS = 'WEAK_SHOOTS',
  THIN_STEMS = 'THIN_STEMS',
  LUSH_VEGETATIVE_GROWTH = 'LUSH_VEGETATIVE_GROWTH',
  UNEQUAL_PLANT_HEIGHT = 'UNEQUAL_PLANT_HEIGHT',
  PLANTS_LODGING = 'PLANTS_LODGING',
  
  // C. LEAF-BASED OBSERVATIONS (Most Common Farmer Inputs)
  
  // 1. COLOR & VIGOR
  LEAF_YELLOWING = 'LEAF_YELLOWING',
  INTERVEINAL_CHLOROSIS = 'INTERVEINAL_CHLOROSIS',
  LEAF_PALE_GREEN = 'LEAF_PALE_GREEN',
  LEAF_REDDENING = 'LEAF_REDDENING',
  LEAF_BROWN_TIPS = 'LEAF_BROWN_TIPS',
  LEAF_SCORCHING = 'LEAF_SCORCHING',
  LEAF_DRYING = 'LEAF_DRYING',
  LEAF_WILTING = 'LEAF_WILTING',
  LEAF_ROLLING = 'LEAF_ROLLING',
  
  // 2. SHAPE & STRUCTURE
  LEAF_CURLING = 'LEAF_CURLING',
  LEAF_CRINKLING = 'LEAF_CRINKLING',
  LEAF_DISTORTION = 'LEAF_DISTORTION',
  LEAF_TWISTING = 'LEAF_TWISTING',
  LEAF_NARROWING = 'LEAF_NARROWING',
  LEAF_DROOPING = 'LEAF_DROOPING',
  
  // 3. SPOTS, MARKS & GROWTHS
  LEAF_SPOTS_PRESENT = 'LEAF_SPOTS_PRESENT',
  LEAF_STRIPES_PRESENT = 'LEAF_STRIPES_PRESENT',
  LEAF_BLIGHTED = 'LEAF_BLIGHTED',
  LEAF_BLAST_SYMPTOMS = 'LEAF_BLAST_SYMPTOMS',
  LEAF_MOSAIC_PATTERN = 'LEAF_MOSAIC_PATTERN',
  LEAF_PUSTULES = 'LEAF_PUSTULES',
  LEAF_WHITE_PATCHES = 'LEAF_WHITE_PATCHES',
  LEAF_BLACK_PATCHES = 'LEAF_BLACK_PATCHES',
  
  // D. STEM / SHOOT / CROWN OBSERVATIONS
  DEAD_HEART_PRESENT = 'DEAD_HEART_PRESENT',
  CENTRAL_SHOOT_DRY = 'CENTRAL_SHOOT_DRY',
  STEM_BORING_MARKS = 'STEM_BORING_MARKS',
  STEM_HOLES_VISIBLE = 'STEM_HOLES_VISIBLE',
  STEM_SPLITTING = 'STEM_SPLITTING',
  STEM_SOFTENING = 'STEM_SOFTENING',
  STEM_ROT_PRESENT = 'STEM_ROT_PRESENT',
  CROWN_ROT_PRESENT = 'CROWN_ROT_PRESENT',
  BASE_DISCOLORATION = 'BASE_DISCOLORATION',
  
  // E. ROOT OBSERVATIONS (If Farmer Pulls Plant)
  ROOT_BROWNING = 'ROOT_BROWNING',
  ROOT_BLACKENING = 'ROOT_BLACKENING',
  ROOT_SOFT = 'ROOT_SOFT',
  ROOT_DRY = 'ROOT_DRY',
  ROOT_POOR_DEVELOPMENT = 'ROOT_POOR_DEVELOPMENT',
  ROOT_GALLS_PRESENT = 'ROOT_GALLS_PRESENT',
  ROOT_NEMATODE_SIGNS = 'ROOT_NEMATODE_SIGNS',
  ROOT_ROTTED = 'ROOT_ROTTED',
  
  // F. INSECT / PEST OBSERVATIONS (Farmer-Visible)
  
  // 1. Presence & Behavior
  INSECTS_VISIBLE = 'INSECTS_VISIBLE',
  INSECTS_FLYING = 'INSECTS_FLYING',
  INSECTS_CRAWLING = 'INSECTS_CRAWLING',
  INSECTS_JUMPING = 'INSECTS_JUMPING',
  LARVAE_PRESENT = 'LARVAE_PRESENT',
  EGGS_PRESENT = 'EGGS_PRESENT',
  
  // 2. Size / Type (Visual)
  SMALL_INSECTS = 'SMALL_INSECTS',
  MEDIUM_INSECTS = 'MEDIUM_INSECTS',
  LARGE_INSECTS = 'LARGE_INSECTS',
  GREEN_INSECTS = 'GREEN_INSECTS',
  BLACK_INSECTS = 'BLACK_INSECTS',
  BROWN_INSECTS = 'BROWN_INSECTS',
  WHITE_INSECTS = 'WHITE_INSECTS',
  
  // 3. Damage Pattern
  LEAF_CHEWING = 'LEAF_CHEWING',
  LEAF_SKELETONIZATION = 'LEAF_SKELETONIZATION',
  LEAF_MINING = 'LEAF_MINING',
  LEAF_WEBBING = 'LEAF_WEBBING',
  STEM_BORING = 'STEM_BORING',
  ROOT_FEEDING = 'ROOT_FEEDING',
  
  // G. DISEASE-SPECIFIC VISUAL SIGNS
  FUNGAL_GROWTH_VISIBLE = 'FUNGAL_GROWTH_VISIBLE',
  WHITE_POWDERY_GROWTH = 'WHITE_POWDERY_GROWTH',
  GREY_MOLD_PRESENT = 'GREY_MOLD_PRESENT',
  BLACK_SOOTY_MOLD = 'BLACK_SOOTY_MOLD',
  BACTERIAL_OOZE = 'BACTERIAL_OOZE',
  WATER_SOAKED_LESIONS = 'WATER_SOAKED_LESIONS',
  FOUL_SMELL_PRESENT = 'FOUL_SMELL_PRESENT',
  RUST_PUSTULES = 'RUST_PUSTULES',
  WILT_SYMPTOM = 'WILT_SYMPTOM',
  GUMMOSIS = 'GUMMOSIS',
  
  // H. NUTRIENT DEFICIENCY INDICATORS (Symptoms – NOT diagnosis)
  UNIFORM_YELLOWING_OLDER_LEAVES = 'UNIFORM_YELLOWING_OLDER_LEAVES',
  UNIFORM_YELLOWING_YOUNG_LEAVES = 'UNIFORM_YELLOWING_YOUNG_LEAVES',
  PURPLISH_LEAVES = 'PURPLISH_LEAVES',
  LEAF_MARGIN_BURN = 'LEAF_MARGIN_BURN',
  TIP_BURN = 'TIP_BURN',
  SMALL_LEAVES = 'SMALL_LEAVES',
  THICK_LEAVES = 'THICK_LEAVES',
  BRITTLE_LEAVES = 'BRITTLE_LEAVES',
  
  // I. FLOWER / REPRODUCTIVE STAGE
  POOR_FLOWERING = 'POOR_FLOWERING',
  FLOWER_DROP = 'FLOWER_DROP',
  BUD_DROP = 'BUD_DROP',
  DELAYED_FLOWERING = 'DELAYED_FLOWERING',
  IRREGULAR_FLOWERING = 'IRREGULAR_FLOWERING',
  
  // J. FRUIT / POD / EAR / PANICLE STAGE
  POOR_FRUIT_SET = 'POOR_FRUIT_SET',
  FRUIT_DROP = 'FRUIT_DROP',
  FRUIT_DEFORMED = 'FRUIT_DEFORMED',
  FRUIT_CRACKING = 'FRUIT_CRACKING',
  FRUIT_ROT = 'FRUIT_ROT',
  SMALL_FRUITS = 'SMALL_FRUITS',
  EMPTY_GRAINS = 'EMPTY_GRAINS',
  PARTIALLY_FILLED_GRAINS = 'PARTIALLY_FILLED_GRAINS',
  
  // K. FIELD-LEVEL & PATTERN OBSERVATIONS (Critical for NDVI correlation)
  PATCHY_DAMAGE = 'PATCHY_DAMAGE',
  EDGE_DAMAGE_ONLY = 'EDGE_DAMAGE_ONLY',
  LOW_LYING_AREA_AFFECTED = 'LOW_LYING_AREA_AFFECTED',
  ENTIRE_FIELD_AFFECTED = 'ENTIRE_FIELD_AFFECTED',
  LOCALIZED_SPOTS = 'LOCALIZED_SPOTS',
  DIRECTIONAL_SPREAD = 'DIRECTIONAL_SPREAD',
  
  // L. WATER & SOIL CONTEXT (Farmer-Observed)
  FIELD_WATERLOGGED = 'FIELD_WATERLOGGED',
  SOIL_TOO_DRY = 'SOIL_TOO_DRY',
  CRACKS_IN_SOIL = 'CRACKS_IN_SOIL',
  SALT_CRUST_VISIBLE = 'SALT_CRUST_VISIBLE',
  WHITE_SOIL_DEPOSITS = 'WHITE_SOIL_DEPOSITS',
  
  // M. WEATHER / EVENT BASED
  DAMAGE_AFTER_RAIN = 'DAMAGE_AFTER_RAIN',
  DAMAGE_AFTER_FROST = 'DAMAGE_AFTER_FROST',
  DAMAGE_AFTER_HEAT = 'DAMAGE_AFTER_HEAT',
  DAMAGE_AFTER_WIND = 'DAMAGE_AFTER_WIND',
  DAMAGE_AFTER_HAIL = 'DAMAGE_AFTER_HAIL',
  
  // N. ADDITIONAL WORLD-CLASS KEYS (ICAR/FAO aligned)
  HONEYDEW_PRESENT = 'HONEYDEW_PRESENT',
  SOOTY_MOLD_ON_HONEYDEW = 'SOOTY_MOLD_ON_HONEYDEW',
  FRASS_VISIBLE = 'FRASS_VISIBLE',
  SILK_WEBBING_VISIBLE = 'SILK_WEBBING_VISIBLE',
  ANTS_PRESENT = 'ANTS_PRESENT',
  TUNNELS_IN_SOIL = 'TUNNELS_IN_SOIL',
  MUD_TUBES_PRESENT = 'MUD_TUBES_PRESENT',
  
  // LEGACY KEYS (for backward compatibility - mapped from old system)
  CROP_UNKNOWN = 'CROP_UNKNOWN',
  CROP_IDENTIFIED = 'CROP_IDENTIFIED',
  AFFECTED_PART_UNKNOWN = 'AFFECTED_PART_UNKNOWN',
  AFFECTED_PART_LEAF = 'AFFECTED_PART_LEAF',
  AFFECTED_PART_STEM = 'AFFECTED_PART_STEM',
  AFFECTED_PART_ROOT = 'AFFECTED_PART_ROOT',
  AFFECTED_PART_FRUIT = 'AFFECTED_PART_FRUIT',
  AFFECTED_PART_WHOLE = 'AFFECTED_PART_WHOLE',
  AFFECTED_PART_FLOWER = 'AFFECTED_PART_FLOWER',
  AFFECTED_PART_BOLL = 'AFFECTED_PART_BOLL',
  DISTRIBUTION_UNKNOWN = 'DISTRIBUTION_UNKNOWN',
  DISTRIBUTION_UNIFORM = 'DISTRIBUTION_UNIFORM',
  DISTRIBUTION_PATCHY = 'DISTRIBUTION_PATCHY',
  DISTRIBUTION_EDGE = 'DISTRIBUTION_EDGE',
  DISTRIBUTION_CENTER = 'DISTRIBUTION_CENTER',
  DISTRIBUTION_SPREADING = 'DISTRIBUTION_SPREADING',
  SEVERITY_UNKNOWN = 'SEVERITY_UNKNOWN',
  SEVERITY_LOW = 'SEVERITY_LOW',
  SEVERITY_MEDIUM = 'SEVERITY_MEDIUM',
  SEVERITY_HIGH = 'SEVERITY_HIGH',
  TIMING_UNKNOWN = 'TIMING_UNKNOWN',
  TIMING_RECENT = 'TIMING_RECENT',
  TIMING_WEEK = 'TIMING_WEEK',
  TIMING_LONG = 'TIMING_LONG',
  INSECT_PRESENT = 'INSECT_PRESENT',
  SYMPTOM_COLOR_CHANGE = 'SYMPTOM_COLOR_CHANGE',
  SYMPTOM_YELLOWING = 'SYMPTOM_YELLOWING',
  SYMPTOM_BROWNING = 'SYMPTOM_BROWNING',
  SYMPTOM_DRYING = 'SYMPTOM_DRYING',
  SYMPTOM_SPOTS = 'SYMPTOM_SPOTS',
  SYMPTOM_HOLES = 'SYMPTOM_HOLES',
  SYMPTOM_WILTING = 'SYMPTOM_WILTING',
  SYMPTOM_CURLING = 'SYMPTOM_CURLING',
  SYMPTOM_STUNTING = 'SYMPTOM_STUNTING',
  SYMPTOM_ROTTING = 'SYMPTOM_ROTTING',
  SYMPTOM_STICKY = 'SYMPTOM_STICKY',
  SYMPTOM_POWDER = 'SYMPTOM_POWDER',
  SYMPTOM_FRASS = 'SYMPTOM_FRASS',
  SYMPTOM_WEBBING = 'SYMPTOM_WEBBING',
  ACTION_SPRAY_DONE = 'ACTION_SPRAY_DONE',
  ACTION_FERTILIZER_APPLIED = 'ACTION_FERTILIZER_APPLIED',
  ACTION_IRRIGATION_DONE = 'ACTION_IRRIGATION_DONE',
  ACTION_NONE = 'ACTION_NONE',
  PHOTO_PROVIDED = 'PHOTO_PROVIDED',
  PHOTO_NOT_PROVIDED = 'PHOTO_NOT_PROVIDED',
  PEST_TYPE_APHID = 'PEST_TYPE_APHID',
  PEST_TYPE_THRIPS = 'PEST_TYPE_THRIPS',
  PEST_TYPE_MITE = 'PEST_TYPE_MITE',
  PEST_TYPE_CATERPILLAR = 'PEST_TYPE_CATERPILLAR',
  PEST_TYPE_UNKNOWN = 'PEST_TYPE_UNKNOWN',
  PEST_TYPE_WHITEFLY = 'PEST_TYPE_WHITEFLY',
  PEST_TYPE_BORER = 'PEST_TYPE_BORER',
  PEST_TYPE_HOPPER = 'PEST_TYPE_HOPPER',
  
  // Insect Behavior Keys
  INSECT_BEHAVIOR_FLYING = 'INSECT_BEHAVIOR_FLYING',
  INSECT_BEHAVIOR_CRAWLING = 'INSECT_BEHAVIOR_CRAWLING',
  INSECT_BEHAVIOR_UNKNOWN = 'INSECT_BEHAVIOR_UNKNOWN',
  BEHAVIOR_FLYING = 'BEHAVIOR_FLYING',
  BEHAVIOR_CRAWLING = 'BEHAVIOR_CRAWLING',
  BEHAVIOR_JUMPING = 'BEHAVIOR_JUMPING',
  BEHAVIOR_STATIONARY = 'BEHAVIOR_STATIONARY',
  
  // Insect Density Keys
  INSECT_DENSITY_FEW = 'INSECT_DENSITY_FEW',
  INSECT_DENSITY_MANY = 'INSECT_DENSITY_MANY',
  INSECT_DENSITY_UNKNOWN = 'INSECT_DENSITY_UNKNOWN',
  
  // Plant Response Keys
  PLANT_RESPONSE_CURLING = 'PLANT_RESPONSE_CURLING',
  PLANT_RESPONSE_YELLOWING = 'PLANT_RESPONSE_YELLOWING',
  PLANT_RESPONSE_STICKY = 'PLANT_RESPONSE_STICKY',
  PLANT_RESPONSE_HOLES = 'PLANT_RESPONSE_HOLES',
  PLANT_RESPONSE_NONE = 'PLANT_RESPONSE_NONE',
  PLANT_RESPONSE_UNKNOWN = 'PLANT_RESPONSE_UNKNOWN',
  RESPONSE_WILTING = 'RESPONSE_WILTING',
  RESPONSE_YELLOWING = 'RESPONSE_YELLOWING',
  RESPONSE_DRYING = 'RESPONSE_DRYING',
  RESPONSE_STUNTED = 'RESPONSE_STUNTED',
  
  // Severity Keys
  SEVERITY_CRITICAL = 'SEVERITY_CRITICAL',
  
  // O. DIAGNOSIS-LEVEL CONFIRMED SYMBOLS
  NITROGEN_DEFICIENCY_CONFIRMED = 'NITROGEN_DEFICIENCY_CONFIRMED',
  PHOSPHORUS_DEFICIENCY_CONFIRMED = 'PHOSPHORUS_DEFICIENCY_CONFIRMED',
  POTASSIUM_DEFICIENCY_CONFIRMED = 'POTASSIUM_DEFICIENCY_CONFIRMED',
  ZINC_DEFICIENCY_CONFIRMED = 'ZINC_DEFICIENCY_CONFIRMED',
  IRON_DEFICIENCY_CONFIRMED = 'IRON_DEFICIENCY_CONFIRMED',
  WATER_STRESS_CONFIRMED = 'WATER_STRESS_CONFIRMED',
}

// Type for a set of observation keys
export type ObservationKeySet = Set<ObservationKey>;

// STAGE-WISE KEY GROUPINGS

export const STAGE_KEYS: Record<string, ObservationKey[]> = {
  germination: [
    ObservationKey.SEED_NOT_GERMINATED,
    ObservationKey.POOR_GERMINATION_PERCENT,
    ObservationKey.GAPS_IN_FIELD,
    ObservationKey.SEEDLING_DIED,
    ObservationKey.SEEDLING_WILTED,
    ObservationKey.SETT_EASILY_PULLED_OUT,
    ObservationKey.ROOTS_SOFT_OR_BLACK,
    ObservationKey.ROOTS_ROTTED,
    ObservationKey.SEED_DECAYED,
    ObservationKey.SEEDLING_YELLOW,
    ObservationKey.SEEDLING_STUNTED,
    ObservationKey.PATCHY_EMERGENCE,
    ObservationKey.IRREGULAR_PLANT_STAND,
    ObservationKey.SOIL_CRUSTING_VISIBLE,
    ObservationKey.WATER_LOGGING_AT_BASE,
    ObservationKey.DRY_SOIL_AT_GERMINATION,
    ObservationKey.MUD_TUBES_PRESENT,
    ObservationKey.TUNNELS_IN_SOIL
  ],
  
  tillering: [
    ObservationKey.DEAD_HEART_PRESENT,
    ObservationKey.POOR_TILLERING,
    ObservationKey.EXCESSIVE_TILLERS,
    ObservationKey.WEAK_SHOOTS,
    ObservationKey.THIN_STEMS,
    ObservationKey.SLOW_GROWTH,
    ObservationKey.STUNTED_PLANTS,
    ObservationKey.LEAF_YELLOWING,
    ObservationKey.LEAF_REDDENING,
    ObservationKey.STEM_BORING_MARKS,
    ObservationKey.CENTRAL_SHOOT_DRY,
    ObservationKey.INSECTS_VISIBLE,
    ObservationKey.LARVAE_PRESENT
  ],
  
  grand_growth: [
    ObservationKey.STEM_BORING_MARKS,
    ObservationKey.STEM_HOLES_VISIBLE,
    ObservationKey.SHORT_INTERNODES,
    ObservationKey.LUSH_VEGETATIVE_GROWTH,
    ObservationKey.LEAF_YELLOWING,
    ObservationKey.INTERVEINAL_CHLOROSIS,
    ObservationKey.WHITE_POWDERY_GROWTH,
    ObservationKey.HONEYDEW_PRESENT,
    ObservationKey.SOOTY_MOLD_ON_HONEYDEW,
    ObservationKey.INSECTS_VISIBLE,
    ObservationKey.WHITE_INSECTS,
    ObservationKey.PLANTS_LODGING
  ],
  
  maturity: [
    ObservationKey.STEM_HOLES_VISIBLE,
    ObservationKey.STEM_ROT_PRESENT,
    ObservationKey.STEM_SOFTENING,
    ObservationKey.LEAF_DRYING,
    ObservationKey.FOUL_SMELL_PRESENT,
    ObservationKey.PLANTS_LODGING,
    ObservationKey.FRUIT_ROT,
    ObservationKey.FRUIT_DEFORMED
  ],
  
  vegetative: [
    ObservationKey.SLOW_GROWTH,
    ObservationKey.STUNTED_PLANTS,
    ObservationKey.LEAF_YELLOWING,
    ObservationKey.LEAF_CURLING,
    ObservationKey.LEAF_SPOTS_PRESENT,
    ObservationKey.INSECTS_VISIBLE,
    ObservationKey.LEAF_CHEWING
  ],
  
  flowering: [
    ObservationKey.POOR_FLOWERING,
    ObservationKey.FLOWER_DROP,
    ObservationKey.BUD_DROP,
    ObservationKey.DELAYED_FLOWERING,
    ObservationKey.IRREGULAR_FLOWERING
  ],
  
  boll_development: [
    ObservationKey.POOR_FRUIT_SET,
    ObservationKey.FRUIT_DROP,
    ObservationKey.FRUIT_DEFORMED,
    ObservationKey.FRUIT_ROT
  ]
};

// CATEGORY MAPPINGS

export const CATEGORY_KEYS: Record<string, ObservationKey[]> = {
  leaf_observations: [
    ObservationKey.LEAF_YELLOWING,
    ObservationKey.LEAF_WILTING,
    ObservationKey.LEAF_CURLING,
    ObservationKey.LEAF_DRYING,
    ObservationKey.LEAF_SPOTS_PRESENT,
    ObservationKey.LEAF_REDDENING,
    ObservationKey.LEAF_BROWN_TIPS,
    ObservationKey.INTERVEINAL_CHLOROSIS,
    ObservationKey.LEAF_CHEWING,
    ObservationKey.LEAF_SKELETONIZATION
  ],
  
  stem_observations: [
    ObservationKey.DEAD_HEART_PRESENT,
    ObservationKey.STEM_BORING_MARKS,
    ObservationKey.STEM_HOLES_VISIBLE,
    ObservationKey.STEM_ROT_PRESENT,
    ObservationKey.STEM_SOFTENING,
    ObservationKey.CENTRAL_SHOOT_DRY
  ],
  
  pest_observations: [
    ObservationKey.INSECTS_VISIBLE,
    ObservationKey.INSECTS_FLYING,
    ObservationKey.INSECTS_CRAWLING,
    ObservationKey.LARVAE_PRESENT,
    ObservationKey.SMALL_INSECTS,
    ObservationKey.GREEN_INSECTS,
    ObservationKey.WHITE_INSECTS,
    ObservationKey.HONEYDEW_PRESENT
  ],
  
  field_pattern: [
    ObservationKey.PATCHY_DAMAGE,
    ObservationKey.EDGE_DAMAGE_ONLY,
    ObservationKey.ENTIRE_FIELD_AFFECTED,
    ObservationKey.LOCALIZED_SPOTS
  ],
  
  soil_water: [
    ObservationKey.FIELD_WATERLOGGED,
    ObservationKey.SOIL_TOO_DRY,
    ObservationKey.CRACKS_IN_SOIL,
    ObservationKey.SALT_CRUST_VISIBLE,
    ObservationKey.WHITE_SOIL_DEPOSITS
  ]
};

// Critical observation keys that are REQUIRED before proceeding to diagnosis.
export const CRITICAL_OBSERVATION_KEYS: ObservationKey[] = [
  ObservationKey.CROP_IDENTIFIED,
  ObservationKey.AFFECTED_PART_LEAF,
  ObservationKey.AFFECTED_PART_STEM,
  ObservationKey.AFFECTED_PART_ROOT,
  ObservationKey.AFFECTED_PART_FRUIT,
  ObservationKey.AFFECTED_PART_WHOLE
];

// Keys that indicate sufficient understanding for each dimension
export const SUFFICIENT_KEYS: Record<string, ObservationKey[]> = {
  crop: [ObservationKey.CROP_IDENTIFIED],
  affected_part: [
    ObservationKey.AFFECTED_PART_LEAF,
    ObservationKey.AFFECTED_PART_STEM,
    ObservationKey.AFFECTED_PART_ROOT,
    ObservationKey.AFFECTED_PART_FRUIT,
    ObservationKey.AFFECTED_PART_WHOLE,
    ObservationKey.AFFECTED_PART_FLOWER,
    ObservationKey.AFFECTED_PART_BOLL
  ],
  distribution: [
    ObservationKey.DISTRIBUTION_UNIFORM,
    ObservationKey.DISTRIBUTION_PATCHY,
    ObservationKey.DISTRIBUTION_EDGE,
    ObservationKey.DISTRIBUTION_CENTER,
    ObservationKey.DISTRIBUTION_SPREADING,
    ObservationKey.PATCHY_DAMAGE,
    ObservationKey.EDGE_DAMAGE_ONLY,
    ObservationKey.ENTIRE_FIELD_AFFECTED,
    ObservationKey.LOCALIZED_SPOTS
  ],
  severity: [
    ObservationKey.SEVERITY_LOW,
    ObservationKey.SEVERITY_MEDIUM,
    ObservationKey.SEVERITY_HIGH
  ],
  timing: [
    ObservationKey.TIMING_RECENT,
    ObservationKey.TIMING_WEEK,
    ObservationKey.TIMING_LONG
  ]
};

// Check if a dimension is satisfied by the given observation keys
export function isDimensionSatisfied(
  keys: Set<ObservationKey>,
  dimension: keyof typeof SUFFICIENT_KEYS
): boolean {
  const requiredKeys = SUFFICIENT_KEYS[dimension];
  return requiredKeys.some(k => keys.has(k));
}

// Get the next unsatisfied dimension in priority order
export function getNextMissingDimension(
  keys: Set<ObservationKey>
): keyof typeof SUFFICIENT_KEYS | null {
  // Priority order: crop → affected_part → distribution → severity → timing
  const priorityOrder: (keyof typeof SUFFICIENT_KEYS)[] = [
    'crop',
    'affected_part',
    'distribution',
    'severity',
    'timing'
  ];
  
  for (const dimension of priorityOrder) {
    if (!isDimensionSatisfied(keys, dimension)) {
      return dimension;
    }
  }
  
  return null; // All dimensions satisfied
}

// Count how many dimensions are satisfied
export function countSatisfiedDimensions(keys: Set<ObservationKey>): number {
  let count = 0;
  for (const dimension of Object.keys(SUFFICIENT_KEYS) as (keyof typeof SUFFICIENT_KEYS)[]) {
    if (isDimensionSatisfied(keys, dimension)) {
      count++;
    }
  }
  return count;
}

// Get observation keys for a specific crop and stage from the STAGE_KEYS mapping
export function getStageObservationKeys(stage: string): ObservationKey[] {
  const normalizedStage = stage.toLowerCase().replace(/[\s-]/g, '_');
  return STAGE_KEYS[normalizedStage] || [];
}

// Get observation keys for a specific category
export function getCategoryObservationKeys(category: string): ObservationKey[] {
  return CATEGORY_KEYS[category] || [];
}

export default {
  ObservationKey,
  CRITICAL_OBSERVATION_KEYS,
  SUFFICIENT_KEYS,
  STAGE_KEYS,
  CATEGORY_KEYS,
  isDimensionSatisfied,
  getNextMissingDimension,
  countSatisfiedDimensions,
  getStageObservationKeys,
  getCategoryObservationKeys,
  OBSERVATION_ONTOLOGY_VERSION
};
