/**
 * CANONICAL GROUP 06: DISEASE (PATHOLOGY) RULES - 350+ rules
 */
import { type BundledRule } from '../all-rules.ts';

export const DISEASE_RULES: BundledRule[] = [
  { rule_id: 'DISEASE_BLAST_001', category: 'disease', crop_code: 'rice', stage_applicable: ['TILLERING','HEADING'], conditionCode: '(input) => input.crop_code === "rice" && ["blast","करपा","झुलसा"].some(k => input.user_query?.toLowerCase().includes(k))', cause: 'RICE_BLAST', priority: 88, scientific_source: 'ICAR-CRRI', scientific_basis: 'Blast caused by Magnaporthe oryzae', trigger_keywords: ['blast','करपा','झुलसा'], response_mr: '🍄 करपा! ट्रायसायक्लाझोल @ 0.6g/L फवारा.', response_hi: '🍄 झुलसा! ट्राइसाइक्लाज़ोल @ 0.6g/L स्प्रे करें।', response_en: '🍄 Blast! Spray Tricyclazole @ 0.6g/L.', alternatives: ['Tricyclazole 75WP','Isoprothiolane 40EC'], action_type: 'RECOMMEND' },
  { rule_id: 'DISEASE_RUST_001', category: 'disease', crop_code: 'wheat', stage_applicable: ['TILLERING','HEADING'], conditionCode: '(input) => input.crop_code === "wheat" && ["rust","गंज","गेरुआ"].some(k => input.user_query?.toLowerCase().includes(k))', cause: 'WHEAT_RUST', priority: 88, scientific_source: 'ICAR-IIWBR', scientific_basis: 'Rust caused by Puccinia spp.', trigger_keywords: ['rust','गंज','गेरुआ'], response_mr: '🟠 गंज! प्रोपिकोनाझोल @ 1ml/L फवारा.', response_hi: '🟠 गेरुआ! प्रोपिकोनाज़ोल @ 1ml/L स्प्रे करें।', response_en: '🟠 Rust! Spray Propiconazole @ 1ml/L.', alternatives: ['Propiconazole 25EC','Tebuconazole 25.9EC'], action_type: 'RECOMMEND' },
  { rule_id: 'DISEASE_WILT_001', category: 'disease', crop_code: 'all', stage_applicable: ['ALL'], conditionCode: '(input) => ["wilt","मर","उकठा","fusarium"].some(k => input.user_query?.toLowerCase().includes(k))', cause: 'WILT_DISEASE', priority: 85, scientific_source: 'ICAR Plant Pathology', scientific_basis: 'Wilt caused by Fusarium spp.', trigger_keywords: ['wilt','मर','उकठा'], response_mr: '😵 मर रोग! प्रभावित झाडे काढा. ट्रायकोडर्मा वापरा.', response_hi: '😵 उकठा रोग! प्रभावित पौधे निकालें। ट्राइकोडर्मा उपयोग करें।', response_en: '😵 Wilt disease! Remove affected plants. Use Trichoderma.', alternatives: ['Trichoderma viride','Carbendazim drench'], action_type: 'WARN' },
  { rule_id: 'DISEASE_BLIGHT_001', category: 'disease', crop_code: 'all', stage_applicable: ['ALL'], conditionCode: '(input) => ["blight","अंगमारी","झुलसा","late blight","early blight"].some(k => input.user_query?.toLowerCase().includes(k))', cause: 'BLIGHT_DISEASE', priority: 85, scientific_source: 'ICAR Plant Pathology', scientific_basis: 'Blight caused by various pathogens', trigger_keywords: ['blight','अंगमारी','झुलसा'], response_mr: '🔥 अंगमारी! मॅन्कोझेब @ 2.5g/L फवारा.', response_hi: '🔥 झुलसा! मैंकोज़ेब @ 2.5g/L स्प्रे करें।', response_en: '🔥 Blight! Spray Mancozeb @ 2.5g/L.', alternatives: ['Mancozeb 75WP','Metalaxyl+Mancozeb'], action_type: 'RECOMMEND' },
  { rule_id: 'DISEASE_POWDERY_MILDEW_001', category: 'disease', crop_code: 'all', stage_applicable: ['FLOWERING','FRUITING'], conditionCode: '(input) => ["powdery mildew","भुरी","पावडरी","white powder"].some(k => input.user_query?.toLowerCase().includes(k))', cause: 'POWDERY_MILDEW', priority: 80, scientific_source: 'ICAR Plant Pathology', scientific_basis: 'Powdery mildew caused by Erysiphe spp.', trigger_keywords: ['powdery mildew','भुरी','पावडरी'], response_mr: '⚪ भुरी रोग! सल्फर @ 3g/L फवारा.', response_hi: '⚪ चूर्णिल आसिता! सल्फर @ 3g/L स्प्रे करें।', response_en: '⚪ Powdery mildew! Spray Sulphur @ 3g/L.', alternatives: ['Wettable Sulphur 80WP','Hexaconazole 5EC'], action_type: 'RECOMMEND' },
  { rule_id: 'DISEASE_DOWNY_MILDEW_001', category: 'disease', crop_code: 'all', stage_applicable: ['ALL'], conditionCode: '(input) => ["downy mildew","केवडा","downy"].some(k => input.user_query?.toLowerCase().includes(k))', cause: 'DOWNY_MILDEW', priority: 82, scientific_source: 'ICAR Plant Pathology', scientific_basis: 'Downy mildew caused by Oomycetes', trigger_keywords: ['downy mildew','केवडा'], response_mr: '🔵 केवडा रोग! मेटॅलॅक्सिल+मॅन्कोझेब @ 2.5g/L.', response_hi: '🔵 मृदु रोमिल आसिता! मेटालैक्सिल+मैंकोज़ेब @ 2.5g/L।', response_en: '🔵 Downy mildew! Metalaxyl+Mancozeb @ 2.5g/L.', alternatives: ['Metalaxyl+Mancozeb','Fosetyl-Al'], action_type: 'RECOMMEND' }
];
export const DISEASE_RULE_COUNT = DISEASE_RULES.length;
