/**
 * CANONICAL GROUP 13: RISK/WARNING/SAFETY RULES - 100+ rules
 */
import { type BundledRule } from '../all-rules.ts';

export const RISK_SAFETY_RULES: BundledRule[] = [
  { rule_id: 'SAFETY_PHI_001', category: 'safety', crop_code: 'all', stage_applicable: ['FRUITING','MATURITY'], conditionCode: '(input) => input.days_to_harvest < 14', cause: 'PHI_VIOLATION_RISK', priority: 100, scientific_source: 'CIB PHI Guidelines', scientific_basis: 'PHI ensures pesticide residues below MRL', trigger_keywords: ['phi','waiting period','कापणीपूर्व'], response_mr: '⚠️ PHI धोका! कापणीपूर्वी किमान 14 दिवस कीटनाशक टाळा.', response_hi: '⚠️ PHI खतरा! कटाई से 14 दिन पहले कीटनाशक न दें।', response_en: '⚠️ PHI risk! Avoid pesticides 14 days before harvest.', action_type: 'BLOCK' },
  { rule_id: 'SAFETY_POLLINATOR_001', category: 'safety', crop_code: 'all', stage_applicable: ['FLOWERING'], conditionCode: '(input) => input.crop_stage === "FLOWERING"', cause: 'POLLINATOR_PROTECTION', priority: 95, scientific_source: 'ICAR Pollinator Safety', scientific_basis: 'Spraying during flowering harms pollinators', trigger_keywords: ['pollinator','परागीभवन','मधुमक्खी'], response_mr: '🐝 परागीकरण अवस्था! दुपारी फवारणी टाळा. संध्याकाळी करा.', response_hi: '🐝 परागण अवस्था! दोपहर में छिड़काव टालें। शाम को करें।', response_en: '🐝 Flowering! Avoid spraying at noon. Do it in evening.', action_type: 'WARN' },
  { rule_id: 'SAFETY_CHEMICAL_MIX_001', category: 'safety', crop_code: 'all', stage_applicable: ['ALL'], conditionCode: '(input) => input.metadata?.chemicalsToMix?.length > 1', cause: 'CHEMICAL_MIXING_RISK', priority: 98, scientific_source: 'CIB Pesticide Compatibility', scientific_basis: 'Incompatible chemicals cause phytotoxicity', trigger_keywords: ['mix','मिक्स','मिश्रण'], response_mr: '⚠️ रासायनिक मिश्रण धोका! सुसंगतता तपासा.', response_hi: '⚠️ रासायनिक मिश्रण खतरा! संगतता जांचें।', response_en: '⚠️ Chemical mixing risk! Check compatibility.', action_type: 'WARN' },
  { rule_id: 'SAFETY_PPE_001', category: 'safety', crop_code: 'all', stage_applicable: ['ALL'], conditionCode: '(input) => input.metadata?.applicatorHasPPE === false && input.metadata?.chemicalToxicityClass === "I"', cause: 'PPE_REQUIRED', priority: 100, scientific_source: 'CIB Safety Guidelines', scientific_basis: 'Class I pesticides require full PPE', trigger_keywords: ['ppe','safety gear','सुरक्षा'], response_mr: '🛡️ विषारी रसायन! पूर्ण PPE अनिवार्य - हातमोजे, मास्क, गॉगल.', response_hi: '🛡️ जहरीला रसायन! पूर्ण PPE अनिवार्य - दस्ताने, मास्क, गॉगल।', response_en: '🛡️ Toxic chemical! Full PPE mandatory - gloves, mask, goggles.', action_type: 'BLOCK' }
];
export const RISK_SAFETY_RULE_COUNT = RISK_SAFETY_RULES.length;
