
DO $$
DECLARE
  v_cid uuid;
  v_cat uuid;
BEGIN
  SELECT company_id, category_id INTO v_cid, v_cat FROM public.master_products WHERE ai_recommendable = true AND product_type = 'pesticide' LIMIT 1;

  INSERT INTO public.master_products (company_id, category_id, name, sku, product_type, brand, status, ai_recommendable, organic_certified, effectiveness_rating, active_ingredients, dosage_instructions, application_method, pest_targets, disease_targets, suitable_crops, pre_harvest_interval_days, spray_volume_per_acre, safety_level, ai_metadata, translations)
  SELECT v_cid, v_cat, n, s, pt, b, 'active', true, true, er, ai::jsonb, di, am, pest::jsonb, dis::jsonb, sc::jsonb, 0, sv::jsonb, 'low', meta::jsonb, tr::jsonb
  FROM (VALUES
    ('Trichogramma chilonis','TRICHOGRAMMA-CHILONIS','pesticide','NBAIR',3.80,'[{"name":"Trichogramma chilonis","percentage":100}]','Release 1.5 lakh eggs/acre in 6-8 splits','RELEASE','["SHOOT_BORER","INTERNODE_BORER","TOP_BORER","STEM_BORER","FRUIT_BORER","HELICOVERPA"]','[]','["SUGARCANE","COTTON","RICE","MAIZE","TOMATO"]','{"min":0,"max":0,"unit":"cards"}','{"ipm_level":4,"efficacy_percent":70,"mode_of_action":"Egg parasitism","timing":"Egg-laying stage repeat 7d","weather_restrictions":"No heavy rain","safety_precautions":["Handle gently"]}','{"mr":"ट्रायकोग्रामा चिलोनिस","hi":"ट्राइकोग्रामा चिलोनिस","en":"Trichogramma chilonis"}'),
    ('HaNPV (Helicoverpa NPV)','HANPV-250LE','pesticide','NBAIR',3.50,'[{"name":"HaNPV","percentage":100}]','250 LE/acre in 200L water evening','FOLIAR_SPRAY','["HELICOVERPA","FRUIT_BORER","BOLLWORM","POD_BORER"]','[]','["COTTON","TOMATO","CHICKPEA","CHILLI"]','{"min":200,"max":200,"unit":"L"}','{"ipm_level":4,"efficacy_percent":65,"mode_of_action":"Viral pathogen","timing":"Evening early instar","weather_restrictions":"No sunlight","safety_precautions":["Evening only"]}','{"mr":"हेलिकोव्हर्पा एनपीव्ही","hi":"हेलिकोवर्पा एनपीवी","en":"HaNPV"}'),
    ('SlNPV (Spodoptera NPV)','SLNPV-250LE','pesticide','NBAIR',3.40,'[{"name":"SlNPV","percentage":100}]','250 LE/acre in 200L water','FOLIAR_SPRAY','["SPODOPTERA","TOBACCO_CATERPILLAR","ARMY_WORM"]','[]','["SOYBEAN","COTTON","GROUNDNUT","TOMATO"]','{"min":200,"max":200,"unit":"L"}','{"ipm_level":4,"efficacy_percent":60,"mode_of_action":"Viral pathogen","timing":"Evening","weather_restrictions":"No sun/rain","safety_precautions":["Evening only"]}','{"mr":"स्पोडोप्टेरा एनपीव्ही","hi":"स्पोडोप्टेरा एनपीवी","en":"SlNPV"}'),
    ('Verticillium lecanii 1.15% WP','VERTICILLIUM-LECANII-1.15WP','pesticide','Multiple',3.40,'[{"name":"Verticillium lecanii","percentage":1.15}]','5g/L water spray','FOLIAR_SPRAY','["WHITEFLY","APHID","THRIPS","MEALYBUG","SCALE_INSECT"]','[]','["COTTON","TOMATO","CHILLI","BRINJAL","OKRA"]','{"min":200,"max":250,"unit":"L"}','{"ipm_level":4,"efficacy_percent":60,"mode_of_action":"Entomopathogenic fungus","timing":"Humidity >70%","weather_restrictions":"High humidity","safety_precautions":["No chemical insecticides"]}','{"mr":"व्हर्टिसिलिअम लेकॅनी","hi":"वर्टिसिलियम लेकेनी","en":"Verticillium lecanii"}'),
    ('Bacillus thuringiensis var. kurstaki','BT-KURSTAKI-WP','pesticide','Multiple',3.60,'[{"name":"Bt kurstaki","percentage":100}]','1-2g/L water 200L/acre','FOLIAR_SPRAY','["FRUIT_BORER","HELICOVERPA","DIAMONDBACK_MOTH","ARMY_WORM","SHOOT_BORER"]','[]','["ALL_CROPS"]','{"min":200,"max":200,"unit":"L"}','{"ipm_level":4,"efficacy_percent":65,"mode_of_action":"Cry protein","timing":"Evening early instar","weather_restrictions":"UV sensitive","safety_precautions":["Evening application"]}','{"mr":"बॅसिलस थुरिंजिएन्सिस","hi":"बैसिलस थूरिंजिएंसिस","en":"Bacillus thuringiensis (Bt)"}'),
    ('Paecilomyces lilacinus 1% WP','PAECILOMYCES-LILACINUS-1WP','pesticide','Multiple',3.30,'[{"name":"Paecilomyces lilacinus","percentage":1}]','Soil: 2.5kg/acre with FYM','SOIL_DRENCH','["ROOT_KNOT_NEMATODE","NEMATODE","CYST_NEMATODE"]','[]','["TOMATO","BRINJAL","OKRA","SUGARCANE","BANANA"]','{"min":0,"max":0,"unit":"kg"}','{"ipm_level":4,"efficacy_percent":55,"mode_of_action":"Nematode egg parasitism","timing":"At sowing with FYM","weather_restrictions":"Soil moisture","safety_precautions":["Organic matter"]}','{"mr":"पेसिलोमायसेस लिलॅसिनस","hi":"पेसिलोमाइसिस लिलासिनस","en":"Paecilomyces lilacinus"}'),
    ('Trichoderma viride 1% WP','TRICHODERMA-VIRIDE-1WP','fungicide','Multiple',3.60,'[{"name":"Trichoderma viride","percentage":1}]','Seed: 10g/kg or Soil: 2.5kg/acre+FYM','SEED_TREATMENT','[]','["WILT","FUSARIUM_WILT","ROOT_ROT","DAMPING_OFF","RHIZOCTONIA"]','["ALL_CROPS"]','{"min":0,"max":0,"unit":"kg"}','{"ipm_level":4,"efficacy_percent":65,"mode_of_action":"Mycoparasitism","timing":"Pre-sowing","weather_restrictions":"No chemical fungicides","safety_precautions":["Avoid chemical fungicides"]}','{"mr":"ट्रायकोडर्मा विरिडी","hi":"ट्राइकोडर्मा विरिडी","en":"Trichoderma viride"}'),
    ('Trichoderma harzianum 2% WP','TRICHODERMA-HARZIANUM-2WP','fungicide','Multiple',3.70,'[{"name":"Trichoderma harzianum","percentage":2}]','Seed: 10g/kg or Soil: 2.5kg/acre','SEED_TREATMENT','[]','["WILT","FUSARIUM_WILT","ROOT_ROT","SCLEROTINIA","DAMPING_OFF"]','["ALL_CROPS"]','{"min":0,"max":0,"unit":"kg"}','{"ipm_level":4,"efficacy_percent":68,"mode_of_action":"Competitive exclusion","timing":"Pre-sowing","weather_restrictions":"No chem fungicide 7d","safety_precautions":["No chemical fungicides"]}','{"mr":"ट्रायकोडर्मा हर्झियानम","hi":"ट्राइकोडर्मा हर्जियानम","en":"Trichoderma harzianum"}'),
    ('Pseudomonas fluorescens 1% WP','PSEUDOMONAS-FLUORESCENS-1WP','fungicide','Multiple',3.50,'[{"name":"Pseudomonas fluorescens","percentage":1}]','Seed: 10g/kg or Foliar: 5g/L','SEED_TREATMENT','[]','["BACTERIAL_LEAF_BLIGHT","BLAST","SHEATH_BLIGHT","WILT","BACTERIAL_WILT"]','["ALL_CROPS"]','{"min":200,"max":200,"unit":"L"}','{"ipm_level":4,"efficacy_percent":60,"mode_of_action":"Antibiosis and ISR","timing":"Seed or foliar","weather_restrictions":"No chemical bactericides","safety_precautions":["No antibiotics"]}','{"mr":"स्यूडोमोनास फ्लुरोसेन्स","hi":"स्यूडोमोनास फ्लुओरेसेंस","en":"Pseudomonas fluorescens"}')
  ) AS t(n,s,pt,b,er,ai,di,am,pest,dis,sc,sv,meta,tr)
  WHERE NOT EXISTS (SELECT 1 FROM public.master_products WHERE name = t.n);
END $$;
