CREATE TABLE public.task_type_map (
  raw_value text PRIMARY KEY,
  canonical text NOT NULL
);

GRANT SELECT ON public.task_type_map TO anon;
GRANT SELECT ON public.task_type_map TO authenticated;
GRANT ALL ON public.task_type_map TO service_role;

ALTER TABLE public.task_type_map ENABLE ROW LEVEL SECURITY;

CREATE POLICY "task_type_map readable by all"
  ON public.task_type_map FOR SELECT
  USING (true);

INSERT INTO public.task_type_map (raw_value, canonical) VALUES
('land_preparation','land_preparation'),
('seed_treatment','seed_treatment'),
('nursery','nursery'),
('sowing','sowing'),
('gap_filling','gap_filling'),
('nutrition','nutrition'),
('micronutrient','micronutrient'),
('irrigation','irrigation'),
('weed_management','weed_management'),
('intercultural','intercultural'),
('pest_management','pest_management'),
('disease_management','disease_management'),
('growth_regulation','growth_regulation'),
('monitoring','monitoring'),
('harvest','harvest'),
('post_harvest','post_harvest'),
('residue_management','residue_management'),
('planning','planning'),
('advisory','advisory'),
('planting','sowing'),
('fertilizer','nutrition'),
('pest','pest_management'),
('disease','disease_management'),
('weather','advisory'),
('safety','advisory'),
('organic','nutrition'),
('सिंचन','irrigation'),
('stress','advisory'),
('decision_gate','advisory'),
('pest_control','pest_management'),
('weed','weed_management'),
('तण नियंत्रण','weed_management'),
('proactive_irrigation','irrigation'),
('खत व्यवस्थापन','nutrition'),
('fallow_restoration','land_preparation'),
('other','advisory'),
('Irrigation','irrigation'),
('growth_promoter','growth_regulation'),
('पेरणी','sowing'),
('मशागत','land_preparation'),
('काढणी','harvest'),
('diagnosis','advisory'),
('soil_preparation','land_preparation'),
('नियोजन','planning'),
('कीड नियंत्रण','pest_management'),
('Fertilization','nutrition'),
('proactive_pest','pest_management'),
('Weeding','weed_management'),
('weeding','weed_management'),
('maturity','advisory'),
('harvesting','harvest'),
('काढणी पश्चात','post_harvest'),
('रोग नियंत्रण','disease_management'),
('reproductive','advisory'),
('लागवड','sowing'),
('Land Preparation','land_preparation'),
('निरीक्षण','monitoring'),
('खत','nutrition'),
('germination','advisory'),
('खुरपणी','weed_management'),
('vegetative_growth','advisory'),
('management','advisory'),
('कापणी','harvest'),
('कापणीनंतरचे व्यवस्थापन','post_harvest'),
('जमीन पुनर्संचयन','land_preparation'),
('जमीन तयार करणे','land_preparation'),
('Harvesting','harvest'),
('जमीन मशागत','land_preparation'),
('जमीन व्यवस्थापन','land_preparation'),
('सेंद्रिय खत','nutrition'),
('soil','land_preparation'),
('निंदणी','weed_management'),
('Pest Management','pest_management'),
('पडीक जमीन','land_preparation'),
('पाणी व्यवस्थापन','irrigation'),
('economics','planning'),
('पोषक','nutrition'),
('भूमीची तयारी','land_preparation'),
('माती आरोग्य','land_preparation'),
('कीड आणि रोग नियंत्रण','pest_management'),
('रोपणी','sowing'),
('विपणन','planning'),
('कीड व रोग नियंत्रण','pest_management'),
('सिंचन आणि निरीक्षण','irrigation'),
('pest_disease','pest_management'),
('सूक्ष्म अन्नद्रव्ये','micronutrient'),
('Pest & Disease Management','pest_management'),
('Soil Health','land_preparation'),
('Soil Management','land_preparation'),
('Soil Restoration','land_preparation'),
('Nutrient Management','nutrition'),
('अन्नद्रव्य','nutrition'),
('आंतरमशागत','intercultural'),
('उगवण','advisory'),
('काढणी नंतर','post_harvest'),
('काढणीनंतरची काळजी','post_harvest'),
('काढणीपूर्व','harvest'),
('Crop Establishment','sowing'),
('कीड व्यवस्थापन','pest_management'),
('गुणवत्ता तपासणी','post_harvest'),
('जमीन पुनर्संचयित करणे','land_preparation'),
('जमीन सुधारणा','land_preparation'),
('Financial Management','planning'),
('तपासणी','monitoring'),
('Field Management','intercultural'),
('पिकाचे निरीक्षण','monitoring'),
('पोषक व्यवस्थापन','nutrition'),
('प्रतवारी','post_harvest'),
('बियाणे','seed_treatment'),
('बियाणे प्रक्रिया','seed_treatment'),
('मळणी','post_harvest'),
('Disease Management','disease_management'),
('माती सुधारणा','land_preparation'),
('वाढ उत्तेजक','growth_regulation'),
('साठवण','post_harvest'),
('Crop Planning','planning'),
('Planting','sowing'),
('Post-Harvest','post_harvest');