-- Update agro_climatic_zones with new columns data
-- First insert new zones that don't exist yet, then update existing

-- MH_WESTERN
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Western Maharashtra', 'MH_WESTERN', 'Maharashtra - Pune, Kolhapur, Sangli, Satara, Solapur', 'Semi-Arid Tropical', 600, 'SW Monsoon (June-Sept)', 22, 40, 10, 32, 55, 'Black Cotton Soil, Medium Black', 'Sugarcane, Grapes, Pomegranate, Onion', 15, 35, 40, '10-01', '11-30', 'High evapotranspiration zone. Drip irrigation essential.', 'Sugarcane-based', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- MH_VIDARBHA
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Vidarbha', 'MH_VIDARBHA', 'Maharashtra - Nagpur, Amravati, Akola, Yavatmal, Wardha, Chandrapur', 'Semi-Arid Tropical', 900, 'SW Monsoon (June-Oct)', 24, 46, 8, 35, 50, 'Black Cotton Soil, Clay Loam', 'Cotton, Soybean, Orange, Tur', 12, 38, 35, '09-15', '11-15', 'Cotton belt. High bollworm pressure.', 'Cotton-Soybean', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- MH_MARATHWADA
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Marathwada', 'MH_MARATHWADA', 'Maharashtra - Aurangabad, Beed, Latur, Osmanabad, Nanded, Parbhani, Jalna, Hingoli', 'Semi-Arid Tropical', 750, 'SW Monsoon (June-Sept)', 23, 44, 10, 34, 48, 'Medium to Deep Black', 'Cotton, Soybean, Sugarcane, Jowar', 15, 36, 40, '09-15', '11-30', 'Drought-prone. White grub endemic.', 'Cotton-Soybean-Jowar', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- MH_NORTH
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('North Maharashtra', 'MH_NORTH', 'Maharashtra - Nashik, Ahmednagar, Dhule, Jalgaon, Nandurbar', 'Semi-Arid Tropical', 550, 'SW Monsoon (June-Sept)', 20, 42, 8, 34, 52, 'Black, Red Laterite', 'Grapes, Onion, Sugarcane, Banana, Cotton', 12, 36, 42, '09-01', '11-30', 'Major grape/onion belt. Downy mildew zone.', 'Grape-Onion-Sugarcane', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- MH_KONKAN
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Konkan', 'MH_KONKAN', 'Maharashtra - Mumbai, Thane, Raigad, Ratnagiri, Sindhudurg', 'Humid Tropical Coastal', 3000, 'SW Monsoon (June-Sept)', 24, 35, 18, 32, 80, 'Laterite, Coastal Alluvial', 'Rice, Coconut, Mango, Cashew', 10, 32, 50, '06-01', '09-30', 'High humidity. Fungal diseases prevalent.', 'Rice-based', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- KA_NORTH
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('North Karnataka', 'KA_NORTH', 'Karnataka - Belgaum, Dharwad, Haveri, Gadag, Bidar, Gulbarga', 'Semi-Arid Tropical', 650, 'SW + NE Monsoon', 22, 42, 12, 34, 52, 'Black Cotton, Red Loamy', 'Sugarcane, Cotton, Jowar, Groundnut', 15, 36, 40, '09-15', '11-30', 'Major sugarcane belt. Red rot endemic.', 'Sugarcane-Cotton', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- KA_SOUTH
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('South Karnataka', 'KA_SOUTH', 'Karnataka - Mysore, Mandya, Hassan, Tumkur, Bangalore Rural', 'Semi-Arid to Sub-Humid', 800, 'SW + NE Monsoon', 20, 36, 14, 30, 60, 'Red Loamy, Laterite', 'Sugarcane, Rice, Ragi, Coconut', 12, 34, 45, '09-01', '12-15', 'Cauvery command. Smut and rust prone.', 'Sugarcane-Rice', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- KA_COASTAL
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Coastal Karnataka', 'KA_COASTAL', 'Karnataka - DK, Udupi, UK', 'Humid Tropical Coastal', 3500, 'SW Monsoon', 24, 34, 18, 32, 85, 'Laterite, Coastal Alluvial', 'Rice, Arecanut, Coconut, Cashew', 8, 32, 55, '06-01', '09-30', 'Very high rainfall. Blast endemic.', 'Rice-Plantation', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- TN_CAUVERY_DELTA
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Cauvery Delta', 'TN_CAUVERY_DELTA', 'Tamil Nadu - Thanjavur, Tiruvarur, Nagapattinam, Cuddalore', 'Humid Coastal', 1100, 'NE Monsoon (Oct-Dec)', 24, 38, 20, 32, 75, 'Alluvial, Clay', 'Rice, Sugarcane, Banana, Coconut', 10, 34, 50, '10-01', '12-31', 'Rice granary of TN. BPH zone. Cyclone-prone.', 'Rice-based', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- TN_WESTERN
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Western Tamil Nadu', 'TN_WESTERN', 'Tamil Nadu - Coimbatore, Erode, Tirupur, Karur, Dindigul', 'Semi-Arid', 650, 'SW + NE Monsoon', 22, 38, 16, 32, 55, 'Red Loamy, Black', 'Cotton, Sugarcane, Banana, Turmeric', 15, 36, 42, '09-01', '11-30', 'Major cotton and turmeric belt.', 'Cotton-Sugarcane', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- GJ_SOUTH
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('South Gujarat', 'GJ_SOUTH', 'Gujarat - Surat, Navsari, Valsad, Bharuch, Tapi', 'Humid Sub-Tropical', 1500, 'SW Monsoon', 24, 40, 12, 35, 70, 'Black, Coastal Alluvial', 'Sugarcane, Rice, Banana, Mango', 12, 36, 45, '06-15', '10-31', 'High rainfall sugarcane zone.', 'Sugarcane-Rice', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- GJ_SAURASHTRA
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Saurashtra', 'GJ_SAURASHTRA', 'Gujarat - Rajkot, Junagadh, Bhavnagar, Amreli, Jamnagar', 'Semi-Arid', 500, 'SW Monsoon', 22, 42, 10, 34, 50, 'Black, Sandy Loam', 'Groundnut, Cotton, Wheat, Onion', 15, 38, 35, '09-01', '11-30', 'Dry farming. Aflatoxin risk.', 'Groundnut-Wheat', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- UP_WESTERN
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Western UP', 'UP_WESTERN', 'UP - Meerut, Muzaffarnagar, Saharanpur, Bijnor, Moradabad', 'Sub-Tropical Semi-Arid', 900, 'SW Monsoon + Winter Rains', 20, 44, 4, 25, 55, 'Alluvial, Clay Loam', 'Sugarcane, Wheat, Rice, Vegetables', 12, 38, 40, '10-01', '04-30', 'Major sugarcane belt of India.', 'Sugarcane-Wheat', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- UP_EASTERN
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Eastern UP', 'UP_EASTERN', 'UP - Gorakhpur, Deoria, Kushinagar, Azamgarh, Varanasi', 'Sub-Tropical Humid', 1100, 'SW Monsoon', 22, 42, 6, 28, 65, 'Alluvial', 'Sugarcane, Rice, Wheat, Potato', 10, 36, 45, '06-15', '10-31', 'Rice-wheat-sugarcane system. Flood-prone.', 'Rice-Wheat-Sugarcane', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- PB_HR_CENTRAL
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Central Punjab-Haryana', 'PB_HR_CENTRAL', 'Punjab - Ludhiana, Jalandhar; Haryana - Karnal, Kurukshetra', 'Sub-Tropical Semi-Arid', 700, 'SW Monsoon + Winter Rains', 18, 44, 2, 22, 50, 'Alluvial, Clay Loam', 'Rice, Wheat, Cotton, Sugarcane', 15, 40, 35, '05-01', '10-31', 'Rice-wheat breadbasket. High input intensive.', 'Rice-Wheat', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- AP_COASTAL
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Coastal Andhra', 'AP_COASTAL', 'AP - Krishna, Guntur, East Godavari, West Godavari', 'Humid Tropical Coastal', 1000, 'SW + NE Monsoon', 24, 42, 18, 34, 75, 'Alluvial, Black', 'Rice, Sugarcane, Cotton, Chilli', 10, 36, 50, '06-01', '12-31', 'Rice bowl of AP. BPH endemic.', 'Rice-Cotton', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- TS_TELANGANA
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Telangana', 'TS_TELANGANA', 'Telangana - Hyderabad, Karimnagar, Warangal, Nalgonda', 'Semi-Arid Tropical', 900, 'SW Monsoon', 22, 44, 12, 35, 55, 'Red, Black', 'Cotton, Rice, Maize, Soybean', 15, 38, 40, '06-15', '11-30', 'Cotton and rice belt. Pink bollworm zone.', 'Cotton-Rice', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- MP_MALWA
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Malwa Plateau', 'MP_MALWA', 'MP - Indore, Ujjain, Dewas, Ratlam, Mandsaur', 'Semi-Arid Sub-Tropical', 900, 'SW Monsoon', 20, 44, 8, 32, 50, 'Black Cotton Soil', 'Soybean, Wheat, Cotton, Gram', 15, 38, 40, '06-15', '10-31', 'Soybean capital of India.', 'Soybean-Wheat', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;

-- MP_NIMAR
INSERT INTO public.agro_climatic_zones (name, zone_code, states_covered, climate_type, avg_rainfall_mm, rainfall_pattern, temp_min_summer, temp_max_summer, temp_min_winter, temp_max_winter, humidity_avg, soil_types, major_crops, spray_wind_threshold_kmph, spray_temp_max, spray_humidity_min, critical_period_start, critical_period_end, notes, cropping_pattern, is_active)
VALUES ('Nimar Valley', 'MP_NIMAR', 'MP - Khandwa, Khargone, Burhanpur, Barwani', 'Semi-Arid Tropical', 800, 'SW Monsoon', 22, 46, 10, 35, 48, 'Black, Mixed', 'Cotton, Banana, Sugarcane, Soybean', 12, 40, 38, '06-01', '10-31', 'Cotton and banana belt. Extreme heat.', 'Cotton-Banana', true)
ON CONFLICT (zone_code) DO UPDATE SET states_covered=EXCLUDED.states_covered, climate_type=EXCLUDED.climate_type, avg_rainfall_mm=EXCLUDED.avg_rainfall_mm, rainfall_pattern=EXCLUDED.rainfall_pattern, temp_min_summer=EXCLUDED.temp_min_summer, temp_max_summer=EXCLUDED.temp_max_summer, temp_min_winter=EXCLUDED.temp_min_winter, temp_max_winter=EXCLUDED.temp_max_winter, humidity_avg=EXCLUDED.humidity_avg, soil_types=EXCLUDED.soil_types, major_crops=EXCLUDED.major_crops, spray_wind_threshold_kmph=EXCLUDED.spray_wind_threshold_kmph, spray_temp_max=EXCLUDED.spray_temp_max, spray_humidity_min=EXCLUDED.spray_humidity_min, critical_period_start=EXCLUDED.critical_period_start, critical_period_end=EXCLUDED.critical_period_end, notes=EXCLUDED.notes;