INSERT INTO public.ui_translations (ui_key, language_code, display_text) VALUES
('germination.question.title','en','Has your crop emerged?'),
('germination.question.title','hi','क्या आपकी फसल उग आई है?'),
('germination.question.title','mr','तुमचे पीक उगवले आहे का?'),
('germination.question.body','en','Conditions look right for emergence on {{land}}. Have you seen sprouts in the field?'),
('germination.question.body','hi','{{land}} पर अंकुरण के लिए स्थिति अनुकूल है। क्या खेत में अंकुर दिख रहे हैं?'),
('germination.question.body','mr','{{land}} वर उगवणीसाठी परिस्थिती अनुकूल आहे. शेतात अंकुर दिसत आहेत का?'),
('germination.answer.yes','en','Yes, sprouts are visible'),
('germination.answer.yes','hi','हाँ, अंकुर दिख रहे हैं'),
('germination.answer.yes','mr','होय, अंकुर दिसत आहेत'),
('germination.answer.no','en','No, nothing has come up'),
('germination.answer.no','hi','नहीं, कुछ नहीं निकला'),
('germination.answer.no','mr','नाही, काहीही उगवले नाही'),
('germination.failure.title','en','Possible establishment failure'),
('germination.failure.title','hi','संभावित अंकुरण विफलता'),
('germination.failure.title','mr','संभाव्य उगवण अपयश'),
('germination.failure.body','en','You reported no emergence on {{land}}. Let us check the cause and plan the next step.'),
('germination.failure.body','hi','आपने {{land}} पर अंकुरण न होने की सूचना दी है। आइए कारण जाँचें और अगला कदम तय करें।'),
('germination.failure.body','mr','तुम्ही {{land}} वर उगवण झाली नसल्याचे कळवले आहे. कारण तपासून पुढील पाऊल ठरवूया.'),
('germination.failure.action','en','Ask the advisor about the cause'),
('germination.failure.action','hi','सलाहकार से कारण पूछें'),
('germination.failure.action','mr','सल्लागाराला कारण विचारा'),
('germination.answered','en','Thank you, recorded.'),
('germination.answered','hi','धन्यवाद, दर्ज कर लिया गया।'),
('germination.answered','mr','धन्यवाद, नोंद झाली.')
ON CONFLICT DO NOTHING;