INSERT INTO public.system_config (config_key, config_value, description) VALUES
  ('spray_max_wind_kmh',            '{"PESTICIDE":12,"FUNGICIDE":10,"HERBICIDE":8,"FOLIAR_FERTILIZER":15,"BIOLOGICAL":15}'::jsonb,
     'decision/weather-safety-gate.ts SPRAY_THRESHOLDS.max_wind_speed by product'),
  ('spray_max_rain_probability_pct','{"PESTICIDE":40,"FUNGICIDE":30,"HERBICIDE":50,"FOLIAR_FERTILIZER":60,"BIOLOGICAL":50}'::jsonb,
     'decision/weather-safety-gate.ts SPRAY_THRESHOLDS.max_rain_probability by product'),
  ('spray_min_temperature_c',       '{"PESTICIDE":15,"FUNGICIDE":12,"HERBICIDE":10,"FOLIAR_FERTILIZER":15,"BIOLOGICAL":18}'::jsonb,
     'decision/weather-safety-gate.ts SPRAY_THRESHOLDS.min_temperature by product'),
  ('spray_max_temperature_c',       '{"PESTICIDE":35,"FUNGICIDE":32,"HERBICIDE":30,"FOLIAR_FERTILIZER":38,"BIOLOGICAL":35}'::jsonb,
     'decision/weather-safety-gate.ts SPRAY_THRESHOLDS.max_temperature by product'),
  ('spray_min_humidity_pct',        '30'::jsonb,       'reserved for future foliar-spray gate'),
  ('spray_rain_window_hours',       '6'::jsonb,        'reserved for future rain-window gate'),
  ('safety_toxicity_warn_threshold','"II"'::jsonb,     'agents/safety-guardian.ts WHO-class at which PPE warning fires'),
  ('safety_phi_min_days',           '{"PHI_BUFFER_DAYS":2}'::jsonb,
     'agents/safety-guardian-types.ts SAFETY_THRESHOLDS.PHI_BUFFER_DAYS'),
  ('safety_mrl_max_residue',        '{}'::jsonb,       'Phase 4 target: master_products.mrl_by_crop'),
  ('diagnosis_terminal_damage_threshold','0.70'::jsonb,
     'decision/diagnosis-only-mode.ts SEVERITY_ESCALATORS floor'),
  ('confidence_threshold_min',      '0.60'::jsonb,     'agents/safety-guardian.ts diagnosticConfidence gate'),
  ('confidence_threshold_recommendation','0.75'::jsonb,
     'agents/safety-guardian-types.ts SAFETY_THRESHOLDS.MIN_CONFIDENCE_FOR_CHEMICAL'),
  ('ndvi_staleness_days_kharif',    '7'::jsonb,        'decision/authoritative-state-loader.ts FRESHNESS_THRESHOLDS.NDVI_DAYS (kharif season)'),
  ('ndvi_staleness_days_rabi',      '10'::jsonb,       'decision/authoritative-state-loader.ts FRESHNESS_THRESHOLDS.NDVI_DAYS (rabi season)'),
  ('soil_data_freshness_days',      '90'::jsonb,       'decision/authoritative-state-loader.ts FRESHNESS_THRESHOLDS.SOIL_TEST_DAYS'),
  ('ndvi_status_thresholds',        '{"EXCELLENT":0.7,"GOOD":0.55,"MODERATE":0.4,"POOR":0.25}'::jsonb,
     'decision/authoritative-state-loader.ts NDVI_THRESHOLDS'),
  ('soil_nutrient_thresholds',      '{"NITROGEN":{"HIGH":350,"ADEQUATE":250,"LOW":150},"PHOSPHORUS":{"HIGH":25,"ADEQUATE":15,"LOW":8},"POTASSIUM":{"HIGH":200,"ADEQUATE":130,"LOW":80}}'::jsonb,
     'decision/authoritative-state-loader.ts SOIL_THRESHOLDS')
ON CONFLICT (config_key) DO NOTHING;