-- Crop Synonyms data insert (all 150+ rows)
INSERT INTO public.crop_synonyms (canonical_crop, variant_name, language_code, variant_type, region) VALUES
-- SUGARCANE
('SUGARCANE', 'sugarcane', 'en', 'standard', 'ALL'),
('SUGARCANE', 'sugar cane', 'en', 'spelling_variant', 'ALL'),
('SUGARCANE', 'cane', 'en', 'abbreviation', 'ALL'),
('SUGARCANE', 'गन्ना', 'hi', 'standard', 'ALL'),
('SUGARCANE', 'ganna', 'hi', 'transliteration', 'ALL'),
('SUGARCANE', 'ऊस', 'mr', 'standard', 'Maharashtra'),
('SUGARCANE', 'oos', 'mr', 'transliteration', 'Maharashtra'),
('SUGARCANE', 'us', 'mr', 'transliteration', 'Maharashtra'),
('SUGARCANE', 'कब्बू', 'mr', 'colloquial', 'Vidarbha'),
('SUGARCANE', 'kabbu', 'mr', 'transliteration', 'Vidarbha'),
('SUGARCANE', 'కబ్బు', 'te', 'standard', 'Telangana'),
('SUGARCANE', 'கரும்பு', 'ta', 'standard', 'Tamil Nadu'),
('SUGARCANE', 'karumbu', 'ta', 'transliteration', 'Tamil Nadu'),
('SUGARCANE', 'ಕಬ್ಬು', 'kn', 'standard', 'Karnataka'),
('SUGARCANE', 'kabbu', 'kn', 'transliteration', 'Karnataka'),
('SUGARCANE', 'શેરડી', 'gu', 'standard', 'Gujarat'),
('SUGARCANE', 'sherdi', 'gu', 'transliteration', 'Gujarat'),
('SUGARCANE', 'আখ', 'bn', 'standard', 'West Bengal'),
('SUGARCANE', 'aakh', 'bn', 'transliteration', 'West Bengal'),
('SUGARCANE', 'ratoon', 'en', 'crop_type', 'ALL'),
('SUGARCANE', 'ratoon cane', 'en', 'crop_type', 'ALL'),
('SUGARCANE', 'खोडवा', 'mr', 'crop_type', 'Maharashtra'),
('SUGARCANE', 'khodwa', 'mr', 'transliteration', 'Maharashtra'),
('SUGARCANE', 'पेडी', 'hi', 'crop_type', 'UP'),
('SUGARCANE', 'pedi', 'hi', 'transliteration', 'UP'),
-- COTTON
('COTTON', 'cotton', 'en', 'standard', 'ALL'),
('COTTON', 'kapas', 'hi', 'standard', 'ALL'),
('COTTON', 'कपास', 'hi', 'standard', 'ALL'),
('COTTON', 'कापूस', 'mr', 'standard', 'Maharashtra'),
('COTTON', 'kapus', 'mr', 'transliteration', 'Maharashtra'),
('COTTON', 'bt cotton', 'en', 'variety_type', 'ALL'),
('COTTON', 'bt kapas', 'hi', 'variety_type', 'ALL'),
('COTTON', 'desi cotton', 'en', 'variety_type', 'ALL'),
('COTTON', 'देसी कपास', 'hi', 'variety_type', 'ALL'),
('COTTON', 'american cotton', 'en', 'variety_type', 'ALL'),
('COTTON', 'పత్తి', 'te', 'standard', 'Telangana/AP'),
('COTTON', 'patti', 'te', 'transliteration', 'Telangana/AP'),
('COTTON', 'ಹತ್ತಿ', 'kn', 'standard', 'Karnataka'),
('COTTON', 'hatti', 'kn', 'transliteration', 'Karnataka'),
('COTTON', 'பருத்தி', 'ta', 'standard', 'Tamil Nadu'),
('COTTON', 'paruthi', 'ta', 'transliteration', 'Tamil Nadu'),
('COTTON', 'કપાસ', 'gu', 'standard', 'Gujarat'),
('COTTON', 'narma', 'hi', 'colloquial', 'Punjab/Haryana'),
('COTTON', 'नरमा', 'hi', 'colloquial', 'Punjab/Haryana'),
-- RICE
('RICE', 'rice', 'en', 'standard', 'ALL'),
('RICE', 'paddy', 'en', 'standard', 'ALL'),
('RICE', 'धान', 'hi', 'standard', 'ALL'),
('RICE', 'dhan', 'hi', 'transliteration', 'ALL'),
('RICE', 'चावल', 'hi', 'processed', 'ALL'),
('RICE', 'chawal', 'hi', 'transliteration', 'ALL'),
('RICE', 'भात', 'mr', 'standard', 'Maharashtra'),
('RICE', 'bhat', 'mr', 'transliteration', 'Maharashtra'),
('RICE', 'तांदूळ', 'mr', 'processed', 'Maharashtra'),
('RICE', 'tandul', 'mr', 'transliteration', 'Maharashtra'),
('RICE', 'వరి', 'te', 'standard', 'Telangana/AP'),
('RICE', 'vari', 'te', 'transliteration', 'Telangana/AP'),
('RICE', 'நெல்', 'ta', 'standard', 'Tamil Nadu'),
('RICE', 'nel', 'ta', 'transliteration', 'Tamil Nadu'),
('RICE', 'அரிசி', 'ta', 'processed', 'Tamil Nadu'),
('RICE', 'arisi', 'ta', 'transliteration', 'Tamil Nadu'),
('RICE', 'ಭತ್ತ', 'kn', 'standard', 'Karnataka'),
('RICE', 'bhatta', 'kn', 'transliteration', 'Karnataka'),
('RICE', 'ધાન', 'gu', 'standard', 'Gujarat'),
('RICE', 'basmati', 'en', 'variety_type', 'Punjab/Haryana/UP'),
('RICE', 'बासमती', 'hi', 'variety_type', 'Punjab/Haryana/UP'),
('RICE', 'sona masuri', 'en', 'variety_type', 'AP/Telangana'),
('RICE', 'ponni', 'ta', 'variety_type', 'Tamil Nadu'),
-- WHEAT
('WHEAT', 'wheat', 'en', 'standard', 'ALL'),
('WHEAT', 'गेहूं', 'hi', 'standard', 'ALL'),
('WHEAT', 'gehun', 'hi', 'transliteration', 'ALL'),
('WHEAT', 'गहू', 'mr', 'standard', 'Maharashtra'),
('WHEAT', 'gahu', 'mr', 'transliteration', 'Maharashtra'),
('WHEAT', 'ઘઉં', 'gu', 'standard', 'Gujarat'),
('WHEAT', 'ghau', 'gu', 'transliteration', 'Gujarat'),
('WHEAT', 'kanak', 'hi', 'colloquial', 'Punjab/Haryana'),
('WHEAT', 'कनक', 'hi', 'colloquial', 'Punjab/Haryana'),
('WHEAT', 'గోధుమ', 'te', 'standard', 'Telangana/AP'),
('WHEAT', 'godhuma', 'te', 'transliteration', 'Telangana/AP'),
('WHEAT', 'கோதுமை', 'ta', 'standard', 'Tamil Nadu'),
('WHEAT', 'godumai', 'ta', 'transliteration', 'Tamil Nadu'),
('WHEAT', 'ಗೋಧಿ', 'kn', 'standard', 'Karnataka'),
('WHEAT', 'godhi', 'kn', 'transliteration', 'Karnataka'),
-- SOYBEAN
('SOYBEAN', 'soybean', 'en', 'standard', 'ALL'),
('SOYBEAN', 'soya bean', 'en', 'spelling_variant', 'ALL'),
('SOYBEAN', 'soya', 'en', 'abbreviation', 'ALL'),
('SOYBEAN', 'सोयाबीन', 'hi', 'standard', 'ALL'),
('SOYBEAN', 'soyabean', 'hi', 'transliteration', 'ALL'),
('SOYBEAN', 'सोयाबीन', 'mr', 'standard', 'Maharashtra'),
('SOYBEAN', 'bhatmas', 'hi', 'colloquial', 'MP'),
('SOYBEAN', 'भटमास', 'hi', 'colloquial', 'MP'),
('SOYBEAN', 'సోయా చిక్కుడు', 'te', 'standard', 'Telangana'),
('SOYBEAN', 'ಸೋಯಾ ಅವರೆ', 'kn', 'standard', 'Karnataka'),
-- MAIZE
('MAIZE', 'maize', 'en', 'standard', 'ALL'),
('MAIZE', 'corn', 'en', 'standard', 'ALL'),
('MAIZE', 'मक्का', 'hi', 'standard', 'ALL'),
('MAIZE', 'makka', 'hi', 'transliteration', 'ALL'),
('MAIZE', 'मका', 'mr', 'standard', 'Maharashtra'),
('MAIZE', 'bhutta', 'hi', 'colloquial', 'ALL'),
('MAIZE', 'भुट्टा', 'hi', 'colloquial', 'ALL'),
('MAIZE', 'మొక్కజొన్న', 'te', 'standard', 'Telangana/AP'),
('MAIZE', 'మేకే', 'te', 'colloquial', 'Telangana/AP'),
('MAIZE', 'மக்காச்சோளம்', 'ta', 'standard', 'Tamil Nadu'),
('MAIZE', 'ಮೆಕ್ಕೆ ಜೋಳ', 'kn', 'standard', 'Karnataka'),
('MAIZE', 'મકાઈ', 'gu', 'standard', 'Gujarat'),
-- GROUNDNUT
('GROUNDNUT', 'groundnut', 'en', 'standard', 'ALL'),
('GROUNDNUT', 'peanut', 'en', 'standard', 'ALL'),
('GROUNDNUT', 'मूंगफली', 'hi', 'standard', 'ALL'),
('GROUNDNUT', 'moongfali', 'hi', 'transliteration', 'ALL'),
('GROUNDNUT', 'भुईमूग', 'mr', 'standard', 'Maharashtra'),
('GROUNDNUT', 'bhuimug', 'mr', 'transliteration', 'Maharashtra'),
('GROUNDNUT', 'singdana', 'mr', 'colloquial', 'Maharashtra'),
('GROUNDNUT', 'शेंगदाणा', 'mr', 'colloquial', 'Maharashtra'),
('GROUNDNUT', 'వేరుశనగ', 'te', 'standard', 'Telangana/AP'),
('GROUNDNUT', 'verusenaga', 'te', 'transliteration', 'Telangana/AP'),
('GROUNDNUT', 'நிலக்கடலை', 'ta', 'standard', 'Tamil Nadu'),
('GROUNDNUT', 'nilakadalai', 'ta', 'transliteration', 'Tamil Nadu'),
('GROUNDNUT', 'ಕಡಲೆಕಾಯಿ', 'kn', 'standard', 'Karnataka'),
('GROUNDNUT', 'મગફળી', 'gu', 'standard', 'Gujarat'),
-- ONION
('ONION', 'onion', 'en', 'standard', 'ALL'),
('ONION', 'प्याज', 'hi', 'standard', 'ALL'),
('ONION', 'pyaz', 'hi', 'transliteration', 'ALL'),
('ONION', 'कांदा', 'mr', 'standard', 'Maharashtra'),
('ONION', 'kanda', 'mr', 'transliteration', 'Maharashtra'),
('ONION', 'ఉల్లిపాయ', 'te', 'standard', 'Telangana/AP'),
('ONION', 'ullipaya', 'te', 'transliteration', 'Telangana/AP'),
('ONION', 'வெங்காயம்', 'ta', 'standard', 'Tamil Nadu'),
('ONION', 'vengayam', 'ta', 'transliteration', 'Tamil Nadu'),
('ONION', 'ಈರುಳ್ಳಿ', 'kn', 'standard', 'Karnataka'),
('ONION', 'eerulli', 'kn', 'transliteration', 'Karnataka'),
('ONION', 'ડુંગળી', 'gu', 'standard', 'Gujarat'),
('ONION', 'dungli', 'gu', 'transliteration', 'Gujarat'),
-- POTATO
('POTATO', 'potato', 'en', 'standard', 'ALL'),
('POTATO', 'आलू', 'hi', 'standard', 'ALL'),
('POTATO', 'aloo', 'hi', 'transliteration', 'ALL'),
('POTATO', 'alu', 'hi', 'transliteration', 'ALL'),
('POTATO', 'बटाटा', 'mr', 'standard', 'Maharashtra'),
('POTATO', 'batata', 'mr', 'transliteration', 'Maharashtra'),
('POTATO', 'आलु', 'mr', 'colloquial', 'Maharashtra'),
('POTATO', 'బంగాళదుంప', 'te', 'standard', 'Telangana/AP'),
('POTATO', 'bangaladumpa', 'te', 'transliteration', 'Telangana/AP'),
('POTATO', 'உருளைக்கிழங்கு', 'ta', 'standard', 'Tamil Nadu'),
('POTATO', 'urulaikizhangu', 'ta', 'transliteration', 'Tamil Nadu'),
('POTATO', 'ಆಲೂಗಡ್ಡೆ', 'kn', 'standard', 'Karnataka'),
('POTATO', 'alugedde', 'kn', 'transliteration', 'Karnataka'),
('POTATO', 'બટાટા', 'gu', 'standard', 'Gujarat'),
-- TOMATO
('TOMATO', 'tomato', 'en', 'standard', 'ALL'),
('TOMATO', 'टमाटर', 'hi', 'standard', 'ALL'),
('TOMATO', 'tamatar', 'hi', 'transliteration', 'ALL'),
('TOMATO', 'టమాట', 'te', 'standard', 'Telangana/AP'),
('TOMATO', 'tomata', 'te', 'transliteration', 'Telangana/AP'),
('TOMATO', 'தக்காளி', 'ta', 'standard', 'Tamil Nadu'),
('TOMATO', 'thakkali', 'ta', 'transliteration', 'Tamil Nadu'),
('TOMATO', 'ಟೊಮ್ಯಾಟೊ', 'kn', 'standard', 'Karnataka'),
('TOMATO', 'ટમેટું', 'gu', 'standard', 'Gujarat'),
('TOMATO', 'tametu', 'gu', 'transliteration', 'Gujarat'),
-- CHILLI
('CHILLI', 'chilli', 'en', 'standard', 'ALL'),
('CHILLI', 'chili', 'en', 'spelling_variant', 'ALL'),
('CHILLI', 'mirchi', 'hi', 'standard', 'ALL'),
('CHILLI', 'मिर्च', 'hi', 'standard', 'ALL'),
('CHILLI', 'मिरची', 'mr', 'standard', 'Maharashtra'),
('CHILLI', 'మిర్చి', 'te', 'standard', 'Telangana/AP'),
('CHILLI', 'மிளகாய்', 'ta', 'standard', 'Tamil Nadu'),
('CHILLI', 'milagai', 'ta', 'transliteration', 'Tamil Nadu'),
('CHILLI', 'ಮೆಣಸಿನಕಾಯಿ', 'kn', 'standard', 'Karnataka'),
('CHILLI', 'મરચું', 'gu', 'standard', 'Gujarat'),
('CHILLI', 'marchu', 'gu', 'transliteration', 'Gujarat'),
-- GRAM
('GRAM', 'chickpea', 'en', 'standard', 'ALL'),
('GRAM', 'gram', 'en', 'standard', 'ALL'),
('GRAM', 'bengal gram', 'en', 'standard', 'ALL'),
('GRAM', 'chana', 'hi', 'standard', 'ALL'),
('GRAM', 'चना', 'hi', 'standard', 'ALL'),
('GRAM', 'हरभरा', 'mr', 'standard', 'Maharashtra'),
('GRAM', 'harbhara', 'mr', 'transliteration', 'Maharashtra'),
('GRAM', 'శనగలు', 'te', 'standard', 'Telangana/AP'),
('GRAM', 'senagalu', 'te', 'transliteration', 'Telangana/AP'),
('GRAM', 'கொண்டைக்கடலை', 'ta', 'standard', 'Tamil Nadu'),
('GRAM', 'kondaikadalai', 'ta', 'transliteration', 'Tamil Nadu'),
('GRAM', 'ಕಡಲೆ', 'kn', 'standard', 'Karnataka'),
('GRAM', 'kadale', 'kn', 'transliteration', 'Karnataka'),
('GRAM', 'ચણા', 'gu', 'standard', 'Gujarat'),
-- TUR
('TUR', 'pigeon pea', 'en', 'standard', 'ALL'),
('TUR', 'tur', 'en', 'standard', 'ALL'),
('TUR', 'arhar', 'hi', 'standard', 'ALL'),
('TUR', 'अरहर', 'hi', 'standard', 'ALL'),
('TUR', 'तूर', 'mr', 'standard', 'Maharashtra'),
('TUR', 'కంది', 'te', 'standard', 'Telangana/AP'),
('TUR', 'kandi', 'te', 'transliteration', 'Telangana/AP'),
('TUR', 'துவரை', 'ta', 'standard', 'Tamil Nadu'),
('TUR', 'thuvara', 'ta', 'transliteration', 'Tamil Nadu'),
('TUR', 'ತೊಗರಿ', 'kn', 'standard', 'Karnataka'),
('TUR', 'togari', 'kn', 'transliteration', 'Karnataka'),
('TUR', 'તુવેર', 'gu', 'standard', 'Gujarat'),
('TUR', 'tuver', 'gu', 'transliteration', 'Gujarat')
ON CONFLICT (canonical_crop, variant_name, language_code) DO NOTHING;