
-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 1: Insert 37 missing observation codes into observation_master
-- These are used in decision_rules but have no observation_master entry
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO observation_master (observation_code, description, is_diagnostic, observation_category, affected_plant_part, is_active, is_farmer_observable) VALUES
('CHEMICAL_EXPOSURE', 'Plants exposed to harmful chemicals', false, 'ABIOTIC', 'WHOLE', true, true),
('CROP_STAGE', 'Current crop growth stage query', false, 'MANAGEMENT', 'WHOLE', true, true),
('DATA_QUALITY', 'Data quality verification', false, 'MANAGEMENT', 'WHOLE', true, false),
('DROOPING', 'Plants wilting or drooping', false, 'ABIOTIC', 'WHOLE', true, true),
('ETL_EXCEEDED', 'Pest above economic threshold level', true, 'PEST', 'WHOLE', true, false),
('GENERAL_HEALTH', 'Overall crop health check', false, 'MANAGEMENT', 'WHOLE', true, true),
('GERMINATION_COMPLETE', 'Seeds have germinated', false, 'MANAGEMENT', 'WHOLE', true, true),
('GROWTH_OBSERVATION', 'Plant growth pattern observation', false, 'MANAGEMENT', 'WHOLE', true, true),
('IRRIGATION_NEEDED', 'Crop requires irrigation', false, 'ABIOTIC', 'SOIL', true, true),
('LEAF_DISCOLORATION', 'Abnormal color change in leaves', false, 'NUTRIENT', 'LEAF', true, true),
('LODGING_PRONE_VARIETY', 'Variety susceptible to lodging', false, 'MANAGEMENT', 'STEM', true, true),
('LOW_NDVI', 'Low vegetation index detected', false, 'ABIOTIC', 'WHOLE', true, false),
('LOW_TILLERING', 'Poor tiller formation', false, 'NUTRIENT', 'WHOLE', true, true),
('MATURITY_SIGNS', 'Signs of crop maturity', false, 'MANAGEMENT', 'WHOLE', true, true),
('NDVI_DROP', 'Vegetation index declining', false, 'ABIOTIC', 'WHOLE', true, false),
('PEST_COUNT', 'Number of pests observed', false, 'PEST', 'WHOLE', true, true),
('PEST_POPULATION', 'Pest population level in field', false, 'PEST', 'WHOLE', true, true),
('PLANTING_NEW_CROP', 'Preparing to plant a new crop', false, 'MANAGEMENT', 'WHOLE', true, true),
('PLANTING_PREPARATION', 'Field preparation for planting', false, 'MANAGEMENT', 'SOIL', true, true),
('PRE_HARVEST_INTERVAL', 'Waiting period before harvest', false, 'MANAGEMENT', 'WHOLE', true, false),
('PRE_HARVEST_STAGE', 'Crop in pre-harvest phase', false, 'MANAGEMENT', 'WHOLE', true, true),
('RATOON_INITIATION', 'Starting ratoon crop management', false, 'MANAGEMENT', 'WHOLE', true, true),
('SAFETY_CHECK', 'Safety verification for chemical use', false, 'MANAGEMENT', 'WHOLE', true, false),
('SAFETY_CONCERN', 'Potential safety issue identified', false, 'MANAGEMENT', 'WHOLE', true, false),
('SEED_TREATMENT_NEEDED', 'Seeds require treatment before sowing', false, 'MANAGEMENT', 'WHOLE', true, true),
('SETT_TREATMENT', 'Sugarcane sett treatment before planting', false, 'MANAGEMENT', 'WHOLE', true, true),
('SOIL_BORNE_DISEASE_HISTORY', 'Previous soil-borne disease in field', false, 'DISEASE', 'SOIL', true, true),
('SOIL_CRACKING', 'Cracks visible in soil surface', false, 'ABIOTIC', 'SOIL', true, true),
('STUBBLE_CONDITION', 'Condition of crop stubble after harvest', false, 'MANAGEMENT', 'WHOLE', true, true),
('TALL_CANES', 'Tall sugarcane plants observed', false, 'MANAGEMENT', 'STEM', true, true),
('TEMPERATURE_EXTREME', 'Extreme temperature affecting crop', false, 'ABIOTIC', 'WHOLE', true, true),
('VEGETATION_STRESS', 'Stress indicators in vegetation', false, 'ABIOTIC', 'WHOLE', true, true),
('WEATHER_ALERT', 'Weather warning for farming ops', false, 'ABIOTIC', 'WHOLE', true, false),
('WEATHER_CONDITION', 'Current weather affecting crop', false, 'ABIOTIC', 'WHOLE', true, false),
('WHITE_GRUB_LARVAE', 'White grub larvae in soil', true, 'PEST', 'ROOT', true, true),
('WIND_SPEED', 'High wind speed detected', false, 'ABIOTIC', 'WHOLE', true, false),
('YELLOWING_PATCH', 'Yellow patches visible in field', false, 'NUTRIENT', 'LEAF', true, true)
ON CONFLICT (observation_code) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 2: Insert 66 missing observation translations (en/hi/mr)
-- These codes are used in decision_rules.conditions_json.observations but
-- had ZERO rows in observation_translations, causing English leakage in UI
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO observation_translations (observation_code, language_code, display_text, description_text) VALUES
('NUTRIENT_DEFICIENCY', 'en', 'Nutrient Deficiency', 'Plants showing signs of nutrient shortage'),
('NUTRIENT_DEFICIENCY', 'hi', 'पोषक तत्वों की कमी', 'पौधों में पोषक तत्वों की कमी के लक्षण'),
('NUTRIENT_DEFICIENCY', 'mr', 'अन्नद्रव्यांची कमतरता', 'झाडांमध्ये अन्नद्रव्यांच्या कमतरतेची लक्षणे'),
('PEST_DAMAGE', 'en', 'Pest Damage', 'Visible damage caused by pest attack'),
('PEST_DAMAGE', 'hi', 'कीट क्षति', 'कीटों के हमले से दिखाई देने वाली क्षति'),
('PEST_DAMAGE', 'mr', 'किडीचे नुकसान', 'किडींच्या हल्ल्यामुळे दिसणारे नुकसान'),
('LEAF_DISCOLORATION', 'en', 'Leaf Discoloration', 'Abnormal color change in leaves'),
('LEAF_DISCOLORATION', 'hi', 'पत्ती का रंग बदलना', 'पत्तियों में असामान्य रंग परिवर्तन'),
('LEAF_DISCOLORATION', 'mr', 'पानांचा रंग बदलणे', 'पानांमध्ये असामान्य रंग बदल'),
('LEAF_DAMAGE', 'en', 'Leaf Damage', 'Physical damage visible on leaves'),
('LEAF_DAMAGE', 'hi', 'पत्ती क्षति', 'पत्तियों पर दिखाई देने वाली क्षति'),
('LEAF_DAMAGE', 'mr', 'पानांचे नुकसान', 'पानांवर दिसणारे नुकसान'),
('HEAT_STRESS', 'en', 'Heat Stress', 'Plants affected by high temperature'),
('HEAT_STRESS', 'hi', 'ताप तनाव', 'उच्च तापमान से प्रभावित पौधे'),
('HEAT_STRESS', 'mr', 'उष्णतेचा ताण', 'उच्च तापमानामुळे प्रभावित झाडे'),
('DISEASE_SYMPTOMS', 'en', 'Disease Symptoms', 'Signs of plant disease'),
('DISEASE_SYMPTOMS', 'hi', 'रोग के लक्षण', 'पौधों में रोग के संकेत'),
('DISEASE_SYMPTOMS', 'mr', 'रोगाची लक्षणे', 'झाडांमध्ये रोगाचे संकेत'),
('GROWTH_STAGE', 'en', 'Growth Stage Query', 'Questions about current growth stage'),
('GROWTH_STAGE', 'hi', 'वृद्धि अवस्था', 'वर्तमान वृद्धि अवस्था के बारे में प्रश्न'),
('GROWTH_STAGE', 'mr', 'वाढीचा टप्पा', 'सध्याच्या वाढीच्या टप्प्याबद्दल प्रश्न'),
('CROP_STRESS', 'en', 'Crop Stress', 'General stress observed in crop'),
('CROP_STRESS', 'hi', 'फसल तनाव', 'फसल में सामान्य तनाव'),
('CROP_STRESS', 'mr', 'पिकावरील ताण', 'पिकावर दिसणारा सामान्य ताण'),
('WEED_COMPETITION', 'en', 'Weed Competition', 'Weeds competing with crop'),
('WEED_COMPETITION', 'hi', 'खरपतवार प्रतियोगिता', 'फसल के साथ संसाधनों के लिए खरपतवार'),
('WEED_COMPETITION', 'mr', 'तणांची स्पर्धा', 'पिकाशी संसाधनांसाठी तणांची स्पर्धा'),
('SOIL_CONDITION', 'en', 'Soil Condition', 'Soil health or quality issue'),
('SOIL_CONDITION', 'hi', 'मिट्टी की स्थिति', 'मिट्टी के स्वास्थ्य की समस्या'),
('SOIL_CONDITION', 'mr', 'मातीची स्थिती', 'मातीचे आरोग्य किंवा गुणवत्तेचा प्रश्न'),
('WEATHER_DAMAGE', 'en', 'Weather Damage', 'Crop damage due to adverse weather'),
('WEATHER_DAMAGE', 'hi', 'मौसम क्षति', 'प्रतिकूल मौसम से फसल क्षति'),
('WEATHER_DAMAGE', 'mr', 'हवामानाचे नुकसान', 'प्रतिकूल हवामानामुळे पिकाचे नुकसान'),
('NITROGEN_NEED', 'en', 'Nitrogen Requirement', 'Plants need nitrogen fertilizer'),
('NITROGEN_NEED', 'hi', 'नाइट्रोजन की आवश्यकता', 'पौधों को नाइट्रोजन खाद की जरूरत'),
('NITROGEN_NEED', 'mr', 'नत्राची गरज', 'झाडांना नत्र खताची गरज'),
('LOW_TILLERING', 'en', 'Low Tillering', 'Poor tiller formation in crop'),
('LOW_TILLERING', 'hi', 'कम कल्ले', 'फसल में कम कल्ले बनना'),
('LOW_TILLERING', 'mr', 'कमी फुटवे', 'पिकात कमी फुटवे येणे'),
('HARVEST_READINESS', 'en', 'Harvest Readiness', 'Crop ready for harvest'),
('HARVEST_READINESS', 'hi', 'कटाई की तैयारी', 'फसल कटाई के लिए तैयार'),
('HARVEST_READINESS', 'mr', 'कापणीची तयारी', 'पीक कापणीसाठी तयार'),
('BRIX_LEVEL', 'en', 'Brix Level', 'Sugar content measurement'),
('BRIX_LEVEL', 'hi', 'ब्रिक्स स्तर', 'गन्ने में शर्करा मात्रा'),
('BRIX_LEVEL', 'mr', 'ब्रिक्स पातळी', 'उसातील साखरेचे प्रमाण'),
('CANOPY_THINNING', 'en', 'Canopy Thinning', 'Leaf canopy becoming sparse'),
('CANOPY_THINNING', 'hi', 'छत्र विरलन', 'पत्तियों का छत्र पतला होना'),
('CANOPY_THINNING', 'mr', 'पर्णसंभार विरळ होणे', 'पानांचा छत्र विरळ होणे'),
('CHEMICAL_EXPOSURE', 'en', 'Chemical Exposure', 'Plants exposed to harmful chemicals'),
('CHEMICAL_EXPOSURE', 'hi', 'रासायनिक संपर्क', 'हानिकारक रसायनों से प्रभावित'),
('CHEMICAL_EXPOSURE', 'mr', 'रासायनिक संपर्क', 'हानिकारक रसायनांचा प्रभाव'),
('COST_BENEFIT', 'en', 'Cost Benefit Analysis', 'Economic analysis of farming input'),
('COST_BENEFIT', 'hi', 'लागत-लाभ विश्लेषण', 'कृषि निवेश का आर्थिक विश्लेषण'),
('COST_BENEFIT', 'mr', 'खर्च-लाभ विश्लेषण', 'शेती खर्चाचे आर्थिक विश्लेषण'),
('CROP_MANAGEMENT', 'en', 'Crop Management', 'General crop management query'),
('CROP_MANAGEMENT', 'hi', 'फसल प्रबंधन', 'सामान्य फसल प्रबंधन प्रश्न'),
('CROP_MANAGEMENT', 'mr', 'पीक व्यवस्थापन', 'सामान्य पीक व्यवस्थापन प्रश्न'),
('CROP_STAGE', 'en', 'Crop Stage', 'Current crop growth stage'),
('CROP_STAGE', 'hi', 'फसल अवस्था', 'वर्तमान फसल वृद्धि अवस्था'),
('CROP_STAGE', 'mr', 'पिकाचा टप्पा', 'सध्याचा पिकाचा वाढीचा टप्पा'),
('CYPERUS', 'en', 'Cyperus Weed', 'Cyperus sedge weed infestation'),
('CYPERUS', 'hi', 'मोथा खरपतवार', 'मोथा खरपतवार का प्रकोप'),
('CYPERUS', 'mr', 'लव्हाळा तण', 'लव्हाळा तणाचा प्रादुर्भाव'),
('DATA_QUALITY', 'en', 'Data Quality Check', 'Verifying data accuracy'),
('DATA_QUALITY', 'hi', 'डेटा गुणवत्ता जांच', 'डेटा सटीकता की जांच'),
('DATA_QUALITY', 'mr', 'डेटा गुणवत्ता तपासणी', 'डेटा अचूकतेची तपासणी'),
('DROOPING', 'en', 'Plant Drooping', 'Plants wilting or drooping'),
('DROOPING', 'hi', 'पौधे मुरझाना', 'पौधों का मुरझाना या झुकना'),
('DROOPING', 'mr', 'झाडे मलूल होणे', 'झाडे कोमेजणे किंवा खाली झुकणे'),
('ECONOMICS_QUERY', 'en', 'Economics Query', 'Questions about farming economics'),
('ECONOMICS_QUERY', 'hi', 'आर्थिक प्रश्न', 'कृषि अर्थशास्त्र संबंधी प्रश्न'),
('ECONOMICS_QUERY', 'mr', 'आर्थिक प्रश्न', 'शेती अर्थशास्त्राबद्दल प्रश्न'),
('ETL_EXCEEDED', 'en', 'ETL Threshold Exceeded', 'Pest population above threshold'),
('ETL_EXCEEDED', 'hi', 'आर्थिक हानि सीमा पार', 'कीट संख्या सीमा से ऊपर'),
('ETL_EXCEEDED', 'mr', 'आर्थिक नुकसान सीमा ओलांडली', 'कीटक संख्या सीमेपेक्षा जास्त'),
('FERTIGATION', 'en', 'Fertigation', 'Fertilizer through irrigation'),
('FERTIGATION', 'hi', 'फर्टिगेशन', 'सिंचाई के साथ खाद देना'),
('FERTIGATION', 'mr', 'फर्टिगेशन', 'सिंचनातून खत देणे'),
('GENERAL_ADVISORY', 'en', 'General Advisory', 'General farming advice'),
('GENERAL_ADVISORY', 'hi', 'सामान्य सलाह', 'सामान्य कृषि सलाह'),
('GENERAL_ADVISORY', 'mr', 'सामान्य सल्ला', 'सामान्य शेती सल्ला'),
('GENERAL_HEALTH', 'en', 'General Health Check', 'Overall crop health'),
('GENERAL_HEALTH', 'hi', 'सामान्य स्वास्थ्य जांच', 'समग्र फसल स्वास्थ्य'),
('GENERAL_HEALTH', 'mr', 'सामान्य आरोग्य तपासणी', 'एकूण पिकाचे आरोग्य'),
('GERMINATION_COMPLETE', 'en', 'Germination Complete', 'Seeds germinated successfully'),
('GERMINATION_COMPLETE', 'hi', 'अंकुरण पूर्ण', 'बीजों का सफल अंकुरण'),
('GERMINATION_COMPLETE', 'mr', 'उगवण पूर्ण', 'बियांचे यशस्वी उगवण'),
('GROWTH_OBSERVATION', 'en', 'Growth Observation', 'Plant growth patterns'),
('GROWTH_OBSERVATION', 'hi', 'वृद्धि अवलोकन', 'पौधों की वृद्धि का अवलोकन'),
('GROWTH_OBSERVATION', 'mr', 'वाढीचे निरीक्षण', 'झाडांच्या वाढीचे निरीक्षण'),
('IRRIGATION_NEEDED', 'en', 'Irrigation Needed', 'Crop requires water'),
('IRRIGATION_NEEDED', 'hi', 'सिंचाई आवश्यक', 'फसल को पानी की जरूरत'),
('IRRIGATION_NEEDED', 'mr', 'सिंचन आवश्यक', 'पिकाला पाण्याची गरज'),
('LODGING_PRONE_VARIETY', 'en', 'Lodging Prone Variety', 'Variety susceptible to lodging'),
('LODGING_PRONE_VARIETY', 'hi', 'लॉजिंग प्रवण किस्म', 'गिरने की संभावना वाली किस्म'),
('LODGING_PRONE_VARIETY', 'mr', 'लोळण्यास संवेदनशील जात', 'लोळण्याची शक्यता असलेली जात'),
('LOW_NDVI', 'en', 'Low NDVI', 'Low vegetation index'),
('LOW_NDVI', 'hi', 'कम NDVI', 'कम वनस्पति सूचकांक'),
('LOW_NDVI', 'mr', 'कमी NDVI', 'कमी वनस्पती निर्देशांक'),
('MATURITY_SIGNS', 'en', 'Maturity Signs', 'Crop reaching maturity'),
('MATURITY_SIGNS', 'hi', 'परिपक्वता के संकेत', 'फसल परिपक्व होने के संकेत'),
('MATURITY_SIGNS', 'mr', 'पक्वतेची लक्षणे', 'पीक पक्व होत असल्याची लक्षणे'),
('NDVI_DROP', 'en', 'NDVI Drop', 'Vegetation index declining'),
('NDVI_DROP', 'hi', 'NDVI में गिरावट', 'वनस्पति सूचकांक में गिरावट'),
('NDVI_DROP', 'mr', 'NDVI मध्ये घट', 'वनस्पती निर्देशांकात घट'),
('NUTGRASS', 'en', 'Nutgrass Weed', 'Nutgrass weed infestation'),
('NUTGRASS', 'hi', 'मोथा खरपतवार', 'मोथा घास का प्रकोप'),
('NUTGRASS', 'mr', 'नागरमोथा तण', 'नागरमोथा तणाचा प्रादुर्भाव'),
('PEST_COUNT', 'en', 'Pest Count', 'Number of pests observed'),
('PEST_COUNT', 'hi', 'कीट गणना', 'देखे गए कीटों की संख्या'),
('PEST_COUNT', 'mr', 'कीटक गणना', 'दिसलेल्या कीटकांची संख्या'),
('PEST_POPULATION', 'en', 'Pest Population', 'Pest population level'),
('PEST_POPULATION', 'hi', 'कीट जनसंख्या', 'खेत में कीटों का स्तर'),
('PEST_POPULATION', 'mr', 'कीटक लोकसंख्या', 'शेतातील कीटकांची पातळी'),
('PH_IMBALANCE', 'en', 'pH Imbalance', 'Soil pH outside optimal range'),
('PH_IMBALANCE', 'hi', 'pH असंतुलन', 'मिट्टी का pH इष्टतम सीमा से बाहर'),
('PH_IMBALANCE', 'mr', 'pH असंतुलन', 'मातीचा pH इष्टतम मर्यादेबाहेर'),
('PLANTING_NEW_CROP', 'en', 'New Crop Planting', 'Preparing to plant new crop'),
('PLANTING_NEW_CROP', 'hi', 'नई फसल रोपण', 'नई फसल लगाने की तैयारी'),
('PLANTING_NEW_CROP', 'mr', 'नवीन पीक लागवड', 'नवीन पीक लावण्याची तयारी'),
('PLANTING_PREPARATION', 'en', 'Planting Preparation', 'Field preparation for planting'),
('PLANTING_PREPARATION', 'hi', 'रोपण की तैयारी', 'रोपण के लिए खेत की तैयारी'),
('PLANTING_PREPARATION', 'mr', 'लागवड तयारी', 'लागवडीसाठी शेत तयारी'),
('PRE_HARVEST_INTERVAL', 'en', 'Pre-Harvest Interval', 'Waiting period before harvest'),
('PRE_HARVEST_INTERVAL', 'hi', 'कटाई पूर्व अंतराल', 'सुरक्षित कटाई से पहले प्रतीक्षा'),
('PRE_HARVEST_INTERVAL', 'mr', 'कापणीपूर्व कालावधी', 'सुरक्षित कापणीपूर्वी प्रतीक्षा'),
('PRE_HARVEST_STAGE', 'en', 'Pre-Harvest Stage', 'Crop in pre-harvest phase'),
('PRE_HARVEST_STAGE', 'hi', 'कटाई पूर्व अवस्था', 'फसल कटाई पूर्व चरण में'),
('PRE_HARVEST_STAGE', 'mr', 'कापणीपूर्व टप्पा', 'पीक कापणीपूर्व टप्प्यात'),
('RATOON_INITIATION', 'en', 'Ratoon Initiation', 'Starting ratoon crop'),
('RATOON_INITIATION', 'hi', 'रैटून प्रारंभ', 'रैटून फसल प्रबंधन शुरू'),
('RATOON_INITIATION', 'mr', 'खोडवा सुरुवात', 'खोडवा पीक व्यवस्थापन सुरू'),
('SAFETY_CHECK', 'en', 'Safety Check', 'Safety verification'),
('SAFETY_CHECK', 'hi', 'सुरक्षा जांच', 'रसायन उपयोग की सुरक्षा जांच'),
('SAFETY_CHECK', 'mr', 'सुरक्षा तपासणी', 'रसायन वापराची सुरक्षा तपासणी'),
('SAFETY_CONCERN', 'en', 'Safety Concern', 'Potential safety issue'),
('SAFETY_CONCERN', 'hi', 'सुरक्षा चिंता', 'संभावित सुरक्षा समस्या'),
('SAFETY_CONCERN', 'mr', 'सुरक्षा चिंता', 'संभाव्य सुरक्षा समस्या'),
('SEDGE_WEED', 'en', 'Sedge Weed', 'Sedge weed in field'),
('SEDGE_WEED', 'hi', 'मोथा खरपतवार', 'खेत में मोथा प्रकार का खरपतवार'),
('SEDGE_WEED', 'mr', 'लव्हाळा तण', 'शेतातील लव्हाळा प्रकारचे तण'),
('SEED_TREATMENT_NEEDED', 'en', 'Seed Treatment Needed', 'Seeds require treatment'),
('SEED_TREATMENT_NEEDED', 'hi', 'बीज उपचार आवश्यक', 'बुआई से पहले बीज उपचार'),
('SEED_TREATMENT_NEEDED', 'mr', 'बीजप्रक्रिया आवश्यक', 'पेरणीपूर्वी बीजप्रक्रिया'),
('SETT_TREATMENT', 'en', 'Sett Treatment', 'Sugarcane sett treatment'),
('SETT_TREATMENT', 'hi', 'सेट उपचार', 'गन्ने के सेट का उपचार'),
('SETT_TREATMENT', 'mr', 'बेणे प्रक्रिया', 'उसाच्या बेण्यांवर प्रक्रिया'),
('SOIL_BORNE_DISEASE_HISTORY', 'en', 'Soil-Borne Disease History', 'Previous soil disease'),
('SOIL_BORNE_DISEASE_HISTORY', 'hi', 'मृदा जनित रोग इतिहास', 'पूर्व मृदा जनित रोग'),
('SOIL_BORNE_DISEASE_HISTORY', 'mr', 'मातीजन्य रोगांचा इतिहास', 'पूर्वीचे मातीजन्य रोग'),
('SOIL_CRACKING', 'en', 'Soil Cracking', 'Cracks in soil surface'),
('SOIL_CRACKING', 'hi', 'मिट्टी में दरारें', 'मिट्टी की सतह पर दरारें'),
('SOIL_CRACKING', 'mr', 'मातीला भेगा', 'मातीच्या पृष्ठभागावर भेगा'),
('SOIL_HEALTH', 'en', 'Soil Health', 'Overall soil health'),
('SOIL_HEALTH', 'hi', 'मिट्टी स्वास्थ्य', 'समग्र मिट्टी स्वास्थ्य'),
('SOIL_HEALTH', 'mr', 'मातीचे आरोग्य', 'एकूण मातीचे आरोग्य'),
('STAGE_QUERY', 'en', 'Stage Query', 'Growth stage question'),
('STAGE_QUERY', 'hi', 'अवस्था प्रश्न', 'वृद्धि अवस्था का प्रश्न'),
('STAGE_QUERY', 'mr', 'टप्पा प्रश्न', 'वाढीच्या टप्प्याचा प्रश्न'),
('STUBBLE_CONDITION', 'en', 'Stubble Condition', 'Crop stubble condition'),
('STUBBLE_CONDITION', 'hi', 'ठूंठ की स्थिति', 'कटाई के बाद ठूंठ'),
('STUBBLE_CONDITION', 'mr', 'खुंटाची स्थिती', 'कापणीनंतर खुंटाची स्थिती'),
('SYSTEM_CHECK', 'en', 'System Check', 'System health verification'),
('SYSTEM_CHECK', 'hi', 'सिस्टम जांच', 'सिस्टम स्वास्थ्य सत्यापन'),
('SYSTEM_CHECK', 'mr', 'सिस्टम तपासणी', 'सिस्टम आरोग्य सत्यापन'),
('TALL_CANES', 'en', 'Tall Canes', 'Tall sugarcane plants'),
('TALL_CANES', 'hi', 'लंबे गन्ने', 'लंबे गन्ने के पौधे'),
('TALL_CANES', 'mr', 'उंच ऊस', 'उंच उसाची झाडे'),
('TEMPERATURE_EXTREME', 'en', 'Temperature Extreme', 'Extreme temperature'),
('TEMPERATURE_EXTREME', 'hi', 'अत्यधिक तापमान', 'फसल पर अत्यधिक तापमान'),
('TEMPERATURE_EXTREME', 'mr', 'अत्यंत तापमान', 'पिकावर अत्यंत तापमान'),
('VEGETATION_STRESS', 'en', 'Vegetation Stress', 'Stress in vegetation'),
('VEGETATION_STRESS', 'hi', 'वनस्पति तनाव', 'वनस्पति में तनाव'),
('VEGETATION_STRESS', 'mr', 'वनस्पती ताण', 'वनस्पतीमध्ये ताण'),
('WEATHER_ALERT', 'en', 'Weather Alert', 'Weather warning'),
('WEATHER_ALERT', 'hi', 'मौसम चेतावनी', 'कृषि के लिए मौसम चेतावनी'),
('WEATHER_ALERT', 'mr', 'हवामान इशारा', 'शेतीसाठी हवामान इशारा'),
('WEATHER_CONDITION', 'en', 'Weather Condition', 'Current weather'),
('WEATHER_CONDITION', 'hi', 'मौसम की स्थिति', 'फसल को प्रभावित करने वाला मौसम'),
('WEATHER_CONDITION', 'mr', 'हवामान स्थिती', 'पिकावर परिणाम करणारे हवामान'),
('WEED_PRESENCE', 'en', 'Weed Presence', 'Weeds visible in field'),
('WEED_PRESENCE', 'hi', 'खरपतवार उपस्थिति', 'खेत में खरपतवार दिखाई दे रहे'),
('WEED_PRESENCE', 'mr', 'तणांची उपस्थिती', 'शेतात तण दिसत आहेत'),
('WHITE_GRUB_LARVAE', 'en', 'White Grub Larvae', 'White grub larvae in soil'),
('WHITE_GRUB_LARVAE', 'hi', 'सफेद ग्रब लार्वा', 'मिट्टी में सफेद ग्रब के लार्वा'),
('WHITE_GRUB_LARVAE', 'mr', 'पांढरी हुमणी अळी', 'मातीत पांढऱ्या हुमणीच्या अळ्या'),
('WIND_RISK', 'en', 'Wind Risk', 'Risk of wind damage'),
('WIND_RISK', 'hi', 'हवा का खतरा', 'फसल को हवा से नुकसान का खतरा'),
('WIND_RISK', 'mr', 'वाऱ्याचा धोका', 'पिकाला वाऱ्यामुळे नुकसानाचा धोका'),
('WIND_SPEED', 'en', 'Wind Speed', 'High wind speed'),
('WIND_SPEED', 'hi', 'हवा की गति', 'तेज हवा की गति'),
('WIND_SPEED', 'mr', 'वाऱ्याचा वेग', 'जोरदार वाऱ्याचा वेग'),
('YELLOWING_PATCH', 'en', 'Yellowing Patch', 'Yellow patches in field'),
('YELLOWING_PATCH', 'hi', 'पीला धब्बा', 'खेत में पीले धब्बे दिखाई दे रहे'),
('YELLOWING_PATCH', 'mr', 'पिवळा ठिपका', 'शेतात पिवळे ठिपके दिसत आहेत'),
('YIELD_ESTIMATION', 'en', 'Yield Estimation', 'Estimating crop yield'),
('YIELD_ESTIMATION', 'hi', 'उपज अनुमान', 'अपेक्षित फसल उपज का अनुमान'),
('YIELD_ESTIMATION', 'mr', 'उत्पादन अंदाज', 'अपेक्षित पिकाच्या उत्पादनाचा अंदाज')
ON CONFLICT (observation_code, language_code) DO UPDATE SET display_text = EXCLUDED.display_text, description_text = EXCLUDED.description_text;
