
-- =====================================================
-- 1. SEED disease_risk_model (ICAR/FAO validated thresholds)
-- =====================================================

INSERT INTO disease_risk_model (crop_code, disease_code, disease_name_en, disease_name_mr, disease_name_hi, temp_min, temp_max, humidity_min, humidity_max, leaf_wetness_hours_min, rain_mm_min, rain_mm_max, wind_speed_max, stage_applicable, season_applicable, risk_weight, scientific_source, alert_title_en, alert_title_mr, alert_title_hi, alert_message_en, alert_message_mr, alert_message_hi, alert_action_en, alert_action_mr, alert_action_hi, is_active) VALUES
-- SUGARCANE DISEASES
('SUGARCANE', 'SC_RED_ROT', 'Red Rot', 'तांबेरा रोग', 'लाल सड़न', 25, 32, 85, 100, 12, 20, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE','MATURITY'], ARRAY['KHARIF','RABI'], 0.95, 'ICAR-SBI Coimbatore; Viswanathan (2021)', 'Red Rot Risk Alert', 'तांबेरा रोग धोका', 'लाल सड़न जोखिम', 'High risk of Red Rot infection. Temp 25-32°C + humidity >85% + prolonged leaf wetness detected.', 'तांबेरा रोगाचा उच्च धोका. तापमान 25-32°C + आर्द्रता >85% + दीर्घकाळ पानांवर ओलावा.', 'लाल सड़न का उच्च जोखिम. तापमान 25-32°C + नमी >85% + लंबे समय तक पत्ती गीलापन.', 'Apply Carbendazim 50WP (1g/L) drench at stalk base. Remove infected setts immediately.', 'कार्बेन्डाझिम 50WP (1g/L) बुंध्याच्या तळाशी ड्रेंच करा. बाधित बेणे तात्काळ काढा.', 'कार्बेन्डाजिम 50WP (1g/L) तने के आधार पर ड्रेंच करें. संक्रमित सेट्स तुरंत हटाएं.', true),

('SUGARCANE', 'SC_SMUT', 'Smut', 'काणी रोग', 'कंडुआ', 25, 35, 70, 95, NULL, NULL, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF','RABI'], 0.85, 'ICAR-SBI; Singh et al. (2020)', 'Smut Risk Alert', 'काणी रोग धोका', 'कंडुआ जोखिम', 'Smut-conducive conditions: Warm 25-35°C + moderate humidity. Monitor for whip-like structures.', 'काणी रोगास अनुकूल परिस्थिती: उबदार 25-35°C + मध्यम आर्द्रता. चाबूकसारख्या रचनांवर लक्ष ठेवा.', 'कंडुआ अनुकूल स्थितियाँ: गर्म 25-35°C + मध्यम नमी. चाबुक जैसी संरचनाओं पर नज़र रखें.', 'Rogue affected clumps. Apply Triadimefon 25WP (0.5g/L) foliar spray.', 'बाधित गुच्छे काढा. ट्रायडिमेफॉन 25WP (0.5g/L) फवारणी करा.', 'प्रभावित झुंड हटाएं. ट्रायडिमेफॉन 25WP (0.5g/L) पर्ण छिड़काव करें.', true),

('SUGARCANE', 'SC_WILT', 'Wilt', 'मर रोग', 'उकठा', 28, 38, 60, 90, NULL, NULL, 10, NULL, ARRAY['REPRODUCTIVE','MATURITY'], ARRAY['KHARIF'], 0.80, 'ICAR-SBI; Viswanathan & Rao (2011)', 'Wilt Risk Alert', 'मर रोग धोका', 'उकठा जोखिम', 'Wilt-conducive: High temp 28-38°C + waterlogged conditions. Check for internal reddening.', 'मर रोगास अनुकूल: उच्च तापमान 28-38°C + पाणी साचलेली परिस्थिती. आतील लालसरपणा तपासा.', 'उकठा अनुकूल: उच्च तापमान 28-38°C + जलभराव. आंतरिक लालिमा जांचें.', 'Improve drainage. Apply Trichoderma viride (2.5 kg/ha) to soil.', 'निचरा सुधारा. ट्रायकोडर्मा व्हिरिडी (2.5 kg/ha) जमिनीत टाका.', 'जल निकासी सुधारें. ट्राइकोडर्मा विरिडी (2.5 kg/ha) मिट्टी में डालें.', true),

('SUGARCANE', 'SC_GRASSY_SHOOT', 'Grassy Shoot Disease', 'गवती फूट रोग', 'घासी प्ररोह', 20, 35, 70, 100, NULL, NULL, NULL, NULL, ARRAY['GERMINATION','VEGETATIVE'], ARRAY['KHARIF','RABI'], 0.75, 'ICAR-SBI; Rao et al. (2018)', 'Grassy Shoot Alert', 'गवती फूट रोग धोका', 'घासी प्ररोह जोखिम', 'Grassy shoot symptoms may emerge in current conditions. Inspect for thin tillers with narrow leaves.', 'गवती फूट रोगाची लक्षणे सध्याच्या परिस्थितीत दिसू शकतात. पातळ फुटवे आणि अरुंद पाने तपासा.', 'घासी प्ररोह लक्षण वर्तमान स्थितियों में उभर सकते हैं. पतले कल्ले और संकीर्ण पत्तियाँ जांचें.', 'Rogue affected clumps immediately. Use disease-free seed cane. Hot-water treat setts at 50°C/2hr.', 'बाधित गुच्छे तात्काळ काढा. रोगमुक्त बेणे वापरा. बेण्यांना 50°C/2 तास गरम पाण्याची प्रक्रिया करा.', 'प्रभावित झुंड तुरंत हटाएं. रोग-मुक्त बीज गन्ना उपयोग करें. सेट्स को 50°C/2 घंटे गर्म पानी उपचार दें.', true),

('SUGARCANE', 'SC_POKKAH_BOENG', 'Pokkah Boeng', 'पोक्काह बोईंग', 'पोक्काह बोइंग', 28, 36, 80, 100, 8, 10, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.80, 'ICAR-SBI; Vishwakarma et al. (2013)', 'Pokkah Boeng Risk', 'पोक्काह बोईंग धोका', 'पोक्काह बोइंग जोखिम', 'Fusarium conditions: High temp + high humidity + leaf wetness. Watch for chlorotic leaf distortion.', 'फ्युझेरियम अनुकूल: उच्च तापमान + उच्च आर्द्रता + पानांवर ओलावा. पानांचा हरितद्रव्यहीन विकृती तपासा.', 'फ्यूसेरियम अनुकूल: उच्च तापमान + उच्च नमी + पत्ती गीलापन. पत्ती विकृति पर नज़र रखें.', 'Apply Propiconazole 25EC (1ml/L) foliar spray. Ensure proper drainage.', 'प्रोपिकोनॅझोल 25EC (1ml/L) फवारणी करा. योग्य निचरा सुनिश्चित करा.', 'प्रोपिकोनाज़ोल 25EC (1ml/L) पर्ण छिड़काव करें. उचित जल निकासी सुनिश्चित करें.', true),

('SUGARCANE', 'SC_LEAF_SCALD', 'Leaf Scald', 'पान करपा', 'पत्ती झुलसा', 22, 30, 80, 100, 10, 15, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE','MATURITY'], ARRAY['KHARIF','RABI'], 0.75, 'ICAR-SBI; Ricaud et al. (1989)', 'Leaf Scald Risk', 'पान करपा धोका', 'पत्ती झुलसा जोखिम', 'Leaf scald conditions: Temp 22-30°C with high humidity and leaf wetness >10hrs.', 'पान करपा अनुकूल: तापमान 22-30°C + उच्च आर्द्रता + 10 तासांपेक्षा जास्त पानांवर ओलावा.', 'पत्ती झुलसा अनुकूल: तापमान 22-30°C + उच्च नमी + 10 घंटे से अधिक पत्ती गीलापन.', 'Remove affected leaves. Spray Copper Oxychloride 50WP (3g/L).', 'बाधित पाने काढा. कॉपर ऑक्सिक्लोराईड 50WP (3g/L) फवारणी करा.', 'प्रभावित पत्ते हटाएं. कॉपर ऑक्सीक्लोराइड 50WP (3g/L) छिड़काव करें.', true),

-- RICE DISEASES
('RICE', 'RC_BLAST', 'Rice Blast', 'करपा', 'झोंका', 20, 30, 90, 100, 10, 5, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.95, 'IRRI; Ou (1985); ICAR-IIRR', 'Rice Blast Alert', 'करपा रोग धोका', 'झोंका जोखिम', 'Blast-conducive: Temp 20-30°C + humidity >90% + leaf wetness >10hrs. Diamond-shaped lesions likely.', 'करपा अनुकूल: तापमान 20-30°C + आर्द्रता >90% + 10 तासांपेक्षा जास्त ओलावा. हिऱ्याच्या आकाराचे डाग दिसू शकतात.', 'झोंका अनुकूल: तापमान 20-30°C + नमी >90% + 10 घंटे से अधिक गीलापन. हीरे के आकार के धब्बे संभव.', 'Apply Tricyclazole 75WP (0.6g/L) or Isoprothiolane 40EC (1.5ml/L). Avoid excess nitrogen.', 'ट्रायसायक्लाझोल 75WP (0.6g/L) किंवा आयसोप्रोथिओलेन 40EC (1.5ml/L) फवारणी करा. अति नायट्रोजन टाळा.', 'ट्राइसाइक्लाज़ोल 75WP (0.6g/L) या आइसोप्रोथिओलेन 40EC (1.5ml/L) छिड़काव करें. अतिरिक्त नाइट्रोजन से बचें.', true),

('RICE', 'RC_BLB', 'Bacterial Leaf Blight', 'जिवाणू करपा', 'जीवाणु झुलसा', 25, 35, 80, 100, 8, 10, NULL, 20, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.90, 'IRRI; Mew (1987); ICAR-IIRR', 'BLB Risk Alert', 'जिवाणू करपा धोका', 'जीवाणु झुलसा जोखिम', 'BLB conditions: Warm 25-35°C + high humidity + wind-driven rain. Wavy yellow leaf margins expected.', 'जिवाणू करपा अनुकूल: उबदार 25-35°C + उच्च आर्द्रता + वाऱ्यासह पाऊस. पानांच्या कडांवर पिवळे लहरी डाग.', 'जीवाणु झुलसा अनुकूल: गर्म 25-35°C + उच्च नमी + हवा से बारिश. पत्ती किनारों पर पीली लहरदार धारियाँ.', 'Drain excess water. Spray Streptocycline (0.025%) + Copper Oxy (0.25%). Reduce N application.', 'अतिरिक्त पाणी काढा. स्ट्रेप्टोसायक्लिन (0.025%) + कॉपर ऑक्सी (0.25%) फवारणी करा. N कमी करा.', 'अतिरिक्त पानी निकालें. स्ट्रेप्टोसाइक्लिन (0.025%) + कॉपर ऑक्सी (0.25%) छिड़काव. N कम करें.', true),

('RICE', 'RC_SHEATH_BLIGHT', 'Sheath Blight', 'तांदळाची आवरण करपा', 'आवरण अंगमारी', 25, 32, 85, 100, 6, NULL, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.85, 'IRRI; Lee & Rush (1983); ICAR-IIRR', 'Sheath Blight Alert', 'आवरण करपा धोका', 'आवरण अंगमारी जोखिम', 'Sheath blight risk: Temp 25-32°C + humidity >85% + dense canopy. Oval lesions on sheath.', 'आवरण करपा धोका: तापमान 25-32°C + आर्द्रता >85% + दाट छत. आवरणावर अंडाकार डाग.', 'आवरण अंगमारी जोखिम: तापमान 25-32°C + नमी >85% + घना पर्णछत्र. आवरण पर अंडाकार धब्बे.', 'Apply Hexaconazole 5EC (2ml/L) or Validamycin 3L (2ml/L). Maintain wider spacing.', 'हेक्साकोनॅझोल 5EC (2ml/L) किंवा व्हॅलिडामायसिन 3L (2ml/L) फवारणी करा. रुंद अंतर ठेवा.', 'हेक्साकोनाज़ोल 5EC (2ml/L) या वैलिडामाइसिन 3L (2ml/L) छिड़काव करें. चौड़ा अंतर रखें.', true),

-- WHEAT DISEASES
('WHEAT', 'WH_STEM_RUST', 'Stem Rust', 'खोड गंज', 'तना रतुआ', 15, 25, 80, 100, 6, NULL, NULL, NULL, ARRAY['REPRODUCTIVE','MATURITY'], ARRAY['RABI'], 0.90, 'ICAR-IIWBR; Bhardwaj et al. (2019)', 'Stem Rust Alert', 'खोड गंज धोका', 'तना रतुआ जोखिम', 'Stem rust conditions: Cool 15-25°C + high humidity. Red-brown pustules on stems likely.', 'खोड गंज अनुकूल: थंड 15-25°C + उच्च आर्द्रता. खोडावर लाल-तपकिरी पुटकुळ्या दिसू शकतात.', 'तना रतुआ अनुकूल: ठंडा 15-25°C + उच्च नमी. तने पर लाल-भूरे फुंसियाँ संभव.', 'Apply Propiconazole 25EC (1ml/L). Two sprays at 15-day interval.', 'प्रोपिकोनॅझोल 25EC (1ml/L) फवारणी करा. 15 दिवसांच्या अंतराने दोन फवारण्या.', 'प्रोपिकोनाज़ोल 25EC (1ml/L) छिड़काव करें. 15 दिन के अंतराल पर दो छिड़काव.', true),

('WHEAT', 'WH_LEAF_RUST', 'Leaf Rust', 'पान गंज', 'पत्ती रतुआ', 10, 22, 75, 100, 4, NULL, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['RABI'], 0.85, 'ICAR-IIWBR; Prasad et al. (2020)', 'Leaf Rust Alert', 'पान गंज धोका', 'पत्ती रतुआ जोखिम', 'Leaf rust conditions: Cool 10-22°C + high humidity. Orange pustules on upper leaf surface.', 'पान गंज अनुकूल: थंड 10-22°C + उच्च आर्द्रता. पानांच्या वरच्या बाजूस नारिंगी पुटकुळ्या.', 'पत्ती रतुआ अनुकूल: ठंडा 10-22°C + उच्च नमी. पत्ती ऊपरी सतह पर नारंगी फुंसियाँ.', 'Apply Propiconazole 25EC (1ml/L) immediately at first sign.', 'पहिल्या लक्षणावर तात्काळ प्रोपिकोनॅझोल 25EC (1ml/L) फवारणी करा.', 'पहले लक्षण पर तुरंत प्रोपिकोनाज़ोल 25EC (1ml/L) छिड़काव करें.', true),

('WHEAT', 'WH_KARNAL_BUNT', 'Karnal Bunt', 'करनाल बंट', 'करनाल बंट', 18, 24, 85, 100, 8, 5, NULL, NULL, ARRAY['REPRODUCTIVE'], ARRAY['RABI'], 0.80, 'ICAR-IIWBR; Bonde et al. (1997)', 'Karnal Bunt Alert', 'करनाल बंट धोका', 'करनाल बंट जोखिम', 'Karnal bunt conditions during heading: Temp 18-24°C + high humidity + rain. Fishy smell from grains.', 'करनाल बंट परिस्थिती (लोंबी अवस्था): तापमान 18-24°C + उच्च आर्द्रता + पाऊस. दाण्यांना माशांचा वास.', 'करनाल बंट स्थितियाँ (बाली अवस्था): तापमान 18-24°C + उच्च नमी + बारिश. दानों से मछली की गंध.', 'Apply Propiconazole 25EC at boot-leaf stage. Avoid late irrigation.', 'बूट-पान अवस्थेत प्रोपिकोनॅझोल 25EC फवारणी करा. उशीरा सिंचन टाळा.', 'बूट-पत्ती अवस्था में प्रोपिकोनाज़ोल 25EC छिड़काव करें. देर से सिंचाई से बचें.', true),

-- COTTON DISEASES
('COTTON', 'CT_BACTERIAL_BLIGHT', 'Bacterial Blight', 'जिवाणू करपा', 'जीवाणु अंगमारी', 25, 35, 80, 100, NULL, 10, NULL, 15, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.85, 'ICAR-CICR; Kalpana et al. (2016)', 'Cotton Blight Alert', 'कापूस जिवाणू करपा', 'कपास जीवाणु अंगमारी', 'Bacterial blight conditions: Warm + humid + wind-driven rain. Angular leaf spots with water-soaked margins.', 'जिवाणू करपा अनुकूल: उबदार + दमट + वाऱ्यासह पाऊस. कोनीय डाग पाण्याने भिजलेल्या कडांसह.', 'जीवाणु अंगमारी अनुकूल: गर्म + नम + हवा से बारिश. कोणीय धब्बे जल-सिक्त किनारों के साथ.', 'Spray Streptocycline (0.01%) + Copper Oxychloride (0.25%). Remove infected debris.', 'स्ट्रेप्टोसायक्लिन (0.01%) + कॉपर ऑक्सिक्लोराईड (0.25%) फवारणी करा. बाधित अवशेष काढा.', 'स्ट्रेप्टोसाइक्लिन (0.01%) + कॉपर ऑक्सीक्लोराइड (0.25%) छिड़काव. संक्रमित मलबा हटाएं.', true),

('COTTON', 'CT_GREY_MILDEW', 'Grey Mildew', 'करडी भुरी', 'धूसर फफूंदी', 20, 28, 75, 95, NULL, NULL, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.75, 'ICAR-CICR; Mayee (2007)', 'Grey Mildew Alert', 'करडी भुरी धोका', 'धूसर फफूंदी जोखिम', 'Grey mildew conditions: Cool nights + humid days. Grey powdery growth on lower leaves.', 'करडी भुरी अनुकूल: थंड रात्री + दमट दिवस. खालच्या पानांवर करडी भुकटीसारखी वाढ.', 'धूसर फफूंदी अनुकूल: ठंडी रातें + नम दिन. निचली पत्तियों पर धूसर चूर्ण.', 'Apply Wettable Sulphur 80WP (3g/L) or Carbendazim 50WP (1g/L).', 'सल्फर 80WP (3g/L) किंवा कार्बेन्डाझिम 50WP (1g/L) फवारणी करा.', 'सल्फर 80WP (3g/L) या कार्बेन्डाजिम 50WP (1g/L) छिड़काव करें.', true),

('COTTON', 'CT_ALTERNARIA', 'Alternaria Leaf Spot', 'अल्टरनेरिया पान ठिपके', 'अल्टरनेरिया पत्ती धब्बा', 25, 32, 80, 100, 6, 5, NULL, NULL, ARRAY['VEGETATIVE','REPRODUCTIVE'], ARRAY['KHARIF'], 0.80, 'ICAR-CICR; Chattannavar et al. (2010)', 'Alternaria Alert', 'अल्टरनेरिया धोका', 'अल्टरनेरिया जोखिम', 'Alternaria risk: Warm + humid + intermittent rain. Concentric ring lesions on leaves.', 'अल्टरनेरिया धोका: उबदार + दमट + मधूनमधून पाऊस. पानांवर समकेंद्री वर्तुळाकार डाग.', 'अल्टरनेरिया जोखिम: गर्म + नम + रुक-रुक कर बारिश. पत्तियों पर संकेंद्रित वलय धब्बे.', 'Apply Mancozeb 75WP (2.5g/L) or Hexaconazole 5EC (2ml/L).', 'मँकोझेब 75WP (2.5g/L) किंवा हेक्साकोनॅझोल 5EC (2ml/L) फवारणी करा.', 'मैंकोज़ेब 75WP (2.5g/L) या हेक्साकोनाज़ोल 5EC (2ml/L) छिड़काव करें.', true);

-- =====================================================
-- 2. FIX 14 NULL canonical_group decision rules
-- =====================================================

UPDATE decision_rules SET canonical_group = '09_best_practice' WHERE rule_id = 'SC_BP_TRASH_MULCH_IPM_001' AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '04_disease' WHERE rule_id IN ('SC_DISEASE_TRICHODERMA_001', 'SC_DISEASE_SCYLV_001') AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '04_irrigation' WHERE rule_id IN ('PROACTIVE_WATER_STRESS_UNIVERSAL_001', 'PROACTIVE_WATER_STRESS_COTTON_001') AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '05_nutrition' WHERE rule_id IN ('PROACTIVE_NUTRIENT_DEMAND_UNIVERSAL_001', 'SC_MICRO_CA_DEFICIENCY_001') AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '03_observation' WHERE rule_id IN ('PROACTIVE_UNIVERSAL_DASHBOARD_001', 'PROACTIVE_SEASONAL_TRANSITION_001', 'PROACTIVE_WEEKLY_REPORT_001') AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '03_pest' WHERE rule_id IN ('PROACTIVE_PEST_RISK_PINK_BOLLWORM_001', 'PROACTIVE_PEST_RISK_BOLLWORM_001') AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '07_diagnosis' WHERE rule_id = 'SC_NDVI_DIFFERENTIAL_DIAGNOSIS_001' AND canonical_group IS NULL;
UPDATE decision_rules SET canonical_group = '05_soil' WHERE rule_id = 'SC_SOIL_PREPARATION_001' AND canonical_group IS NULL;

-- =====================================================
-- 3. DROP 4 duplicate indexes on ai_chat_messages
-- =====================================================

DROP INDEX IF EXISTS idx_ai_chat_messages_created_at;
DROP INDEX IF EXISTS idx_ai_chat_messages_session_id;
DROP INDEX IF EXISTS idx_chat_messages_tenant_farmer;
DROP INDEX IF EXISTS idx_ai_chat_messages_training_composite;
