-- 2026-09-06 — DATA REMEDIATION (run separately, after review). Nothing here is deleted.
--
-- Verified on the live DB: all 111 duplicate task groups belong to three schedules generated by
-- baseline-db-ssot@1.0.0/1.2.0 on 2026-08-22/24; two are already cancelled. The only ACTIVE one,
-- b9f15e9e-8978-4b6e-a374-279d58fd678e (Rice, sown 2026-02-15, cultivation_method NULL,
-- generation metadata: cultivation_method_unresolved / soil_fertility_class_missing /
-- region_code_unresolved), carries 84 of the 111 groups and 584 overdue pending tasks. It is a
-- historical contaminated schedule: the current generator (1.6.0) refuses to persist without a
-- resolved method and de-duplicates, so no new schedule can reach this state.
--
-- Action: deactivate it the same way the app's DELETE does (soft-delete; tasks preserved as
-- history; fn_release_land_on_schedule_deactivate frees the land). No method is invented.

update public.crop_schedules
   set status = 'cancelled',
       is_active = false,
       metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
         'remediation', jsonb_build_object(
           'at', now(),
           'reason', 'legacy_generator_contamination',
           'details', 'cultivation_method NULL, 84 duplicate task groups, generator baseline-db-ssot@1.0.0; superseded by resolver SSOT fix 20260906120000',
           'tasks_preserved', true)),
       updated_at = now()
 where id = 'b9f15e9e-8978-4b6e-a374-279d58fd678e'
   and is_active = true
   and cultivation_method is null;

-- Verification (read-only):
--   select count(*) from crop_schedules where is_active and status='active' and cultivation_method is null;  -- expect 0
--   select count(*) from (select schedule_id, task_type, task_date, task_name from schedule_tasks t
--     join crop_schedules s on s.id=t.schedule_id where s.is_active and s.status='active'
--     group by 1,2,3,4 having count(*)>1) d;                                                                -- expect 0
-- The 27 duplicate groups on the two already-cancelled schedules are history and are left in place.
