-- Step 1: Insert observation_master entries for technical terms
-- These are monitoring indicators, action types, pest stages, and warning codes

INSERT INTO observation_master (observation_code, description, is_diagnostic, observation_category, affected_plant_part, is_active) VALUES
-- Success indicators
('DEAD_HEARTS_REDUCED_BELOW_5_PERCENT', 'Dead hearts reduced below 5%', false, 'MONITORING', 'WHOLE', true),
('NO_FRESH_BORE_HOLES_VISIBLE', 'No fresh bore holes visible', false, 'MONITORING', 'STEM', true),
('HEALTHY_TILLER_EMERGENCE_RESUMED', 'Healthy tiller emergence resumed', false, 'MONITORING', 'WHOLE', true),
('FRASS_PRODUCTION_STOPPED', 'Frass production stopped', false, 'MONITORING', 'STEM', true),
-- Failure indicators
('DEAD_HEARTS_EXCEEDING_10_PERCENT', 'Dead hearts exceeding 10%', false, 'MONITORING', 'WHOLE', true),
('FRESH_FRASS_VISIBLE_AFTER_7_DAYS', 'Fresh frass visible after 7 days', false, 'MONITORING', 'STEM', true),
('NEW_ENTRY_HOLES_APPEARING', 'New entry holes appearing', false, 'MONITORING', 'STEM', true),
('RESISTANCE_SUSPECTED_NO_MORTALITY', 'Resistance suspected - no mortality', false, 'MONITORING', 'WHOLE', true),
-- Action types
('RECOMMEND', 'Recommendation action type', false, 'ACTION_TYPE', 'WHOLE', true),
('MONITOR', 'Monitor action type', false, 'ACTION_TYPE', 'WHOLE', true),
('BLOCK', 'Block action type', false, 'ACTION_TYPE', 'WHOLE', true),
('SPRAY', 'Spray action type', false, 'ACTION_TYPE', 'WHOLE', true),
('APPLY', 'Apply action type', false, 'ACTION_TYPE', 'WHOLE', true),
-- Pest stages
('LARVAL', 'Larval stage', false, 'PEST_STAGE', 'WHOLE', true),
('EGG', 'Egg stage', false, 'PEST_STAGE', 'WHOLE', true),
('ADULT', 'Adult stage', false, 'PEST_STAGE', 'WHOLE', true),
('PUPAL', 'Pupal stage', false, 'PEST_STAGE', 'WHOLE', true),
('NYMPH', 'Nymph stage', false, 'PEST_STAGE', 'WHOLE', true),
-- Bee warning keys
('BEE_WARNING_HIGH', 'High bee toxicity warning', false, 'SAFETY', 'WHOLE', true),
('BEE_WARNING_MODERATE', 'Moderate bee toxicity warning', false, 'SAFETY', 'WHOLE', true),
-- IPM/control types
('MECHANICAL_PHYSICAL_CONTROL', 'Mechanical/Physical control', false, 'IPM', 'WHOLE', true),
('BIOLOGICAL_CONTROL', 'Biological control', false, 'IPM', 'WHOLE', true),
('CHEMICAL_CONTROL', 'Chemical control (last resort)', false, 'IPM', 'WHOLE', true),
('CULTURAL_CONTROL', 'Cultural control', false, 'IPM', 'WHOLE', true),
-- Treatment types
('TREATMENT', 'Treatment action', false, 'ACTION_TYPE', 'WHOLE', true),
('URGENT_ACTION', 'Urgent action required', false, 'ACTION_TYPE', 'WHOLE', true),
('SEED_TREATMENT', 'Seed treatment', false, 'ACTION_TYPE', 'WHOLE', true),
('SOIL_DRENCH', 'Soil drench application', false, 'ACTION_TYPE', 'WHOLE', true),
('FERTILIZER_APPLICATION', 'Fertilizer application', false, 'ACTION_TYPE', 'WHOLE', true)
ON CONFLICT (observation_code) DO NOTHING;

-- Step 2: Insert translations
INSERT INTO observation_translations (observation_code, language_code, display_text, description_text) VALUES
-- Success indicators
('DEAD_HEARTS_REDUCED_BELOW_5_PERCENT', 'mr', 'मृत गाभे 5% च्या खाली', 'मृत गाभे 5 टक्क्यांच्या खाली आले'),
('DEAD_HEARTS_REDUCED_BELOW_5_PERCENT', 'hi', 'मृत गाभे 5% से कम', 'मृत गाभे 5 प्रतिशत से कम हो गए'),
('DEAD_HEARTS_REDUCED_BELOW_5_PERCENT', 'en', 'Dead hearts reduced below 5%', 'Dead hearts reduced below 5 percent'),
('NO_FRESH_BORE_HOLES_VISIBLE', 'mr', 'नवीन छिद्रे नाहीत', 'नवीन छिद्रे दिसत नाहीत'),
('NO_FRESH_BORE_HOLES_VISIBLE', 'hi', 'नए छेद नहीं', 'नए छेद दिखाई नहीं दे रहे'),
('NO_FRESH_BORE_HOLES_VISIBLE', 'en', 'No fresh bore holes visible', 'No fresh bore holes are visible'),
('HEALTHY_TILLER_EMERGENCE_RESUMED', 'mr', 'निरोगी फुटवे', 'निरोगी फुटवे येत आहेत'),
('HEALTHY_TILLER_EMERGENCE_RESUMED', 'hi', 'स्वस्थ कल्ले', 'स्वस्थ कल्ले निकल रहे हैं'),
('HEALTHY_TILLER_EMERGENCE_RESUMED', 'en', 'Healthy tiller emergence resumed', 'Healthy tillers are emerging again'),
('FRASS_PRODUCTION_STOPPED', 'mr', 'विष्ठा थांबली', 'किडीची विष्ठा दिसत नाही'),
('FRASS_PRODUCTION_STOPPED', 'hi', 'मल बंद', 'कीट का मल दिखाई नहीं दे रहा'),
('FRASS_PRODUCTION_STOPPED', 'en', 'Frass production stopped', 'Insect frass production has stopped'),
-- Failure indicators
('DEAD_HEARTS_EXCEEDING_10_PERCENT', 'mr', 'मृत गाभे 10% पेक्षा जास्त', 'मृत गाभे 10 टक्क्यांपेक्षा जास्त'),
('DEAD_HEARTS_EXCEEDING_10_PERCENT', 'hi', 'मृत गाभे 10% से अधिक', 'मृत गाभे 10 प्रतिशत से अधिक'),
('DEAD_HEARTS_EXCEEDING_10_PERCENT', 'en', 'Dead hearts exceeding 10%', 'Dead hearts exceeding 10 percent'),
('FRESH_FRASS_VISIBLE_AFTER_7_DAYS', 'mr', 'विष्ठा दिसते', '7 दिवसांनंतरही किडीची विष्ठा दिसते'),
('FRESH_FRASS_VISIBLE_AFTER_7_DAYS', 'hi', 'मल दिखाई दे रहा', '7 दिनों के बाद भी कीट का मल दिखाई दे रहा'),
('FRESH_FRASS_VISIBLE_AFTER_7_DAYS', 'en', 'Fresh frass visible after 7 days', 'Fresh frass still visible after 7 days'),
('NEW_ENTRY_HOLES_APPEARING', 'mr', 'नवीन छिद्रे', 'नवीन प्रवेश छिद्रे दिसत आहेत'),
('NEW_ENTRY_HOLES_APPEARING', 'hi', 'नए छेद', 'नए प्रवेश छेद दिखाई दे रहे हैं'),
('NEW_ENTRY_HOLES_APPEARING', 'en', 'New entry holes appearing', 'New entry holes are appearing'),
('RESISTANCE_SUSPECTED_NO_MORTALITY', 'mr', 'प्रतिकार शंकास्पद', 'किडीचा प्रतिकार शंकास्पद'),
('RESISTANCE_SUSPECTED_NO_MORTALITY', 'hi', 'प्रतिरोध आशंका', 'कीट प्रतिरोध की आशंका'),
('RESISTANCE_SUSPECTED_NO_MORTALITY', 'en', 'Resistance suspected - no mortality', 'Resistance suspected with no pest mortality'),
-- Action types
('RECOMMEND', 'mr', 'शिफारस', 'शिफारस केलेली कृती'),
('RECOMMEND', 'hi', 'सिफारिश', 'अनुशंसित कार्रवाई'),
('RECOMMEND', 'en', 'Recommend', 'Recommended action'),
('MONITOR', 'mr', 'निरीक्षण', 'निरीक्षण करा'),
('MONITOR', 'hi', 'निगरानी', 'निगरानी करें'),
('MONITOR', 'en', 'Monitor', 'Continue monitoring'),
('BLOCK', 'mr', 'थांबवा', 'उपचार थांबवा'),
('BLOCK', 'hi', 'रोकें', 'उपचार रोकें'),
('BLOCK', 'en', 'Block', 'Treatment blocked'),
('SPRAY', 'mr', 'फवारणी', 'फवारणी करा'),
('SPRAY', 'hi', 'छिड़काव', 'छिड़काव करें'),
('SPRAY', 'en', 'Spray', 'Spray application'),
('APPLY', 'mr', 'वापरा', 'उपचार वापरा'),
('APPLY', 'hi', 'लगाएं', 'उपचार लगाएं'),
('APPLY', 'en', 'Apply', 'Apply treatment'),
-- Pest stages
('LARVAL', 'mr', 'अळीचा टप्पा', 'अळीचा टप्पा'),
('LARVAL', 'hi', 'लार्वा चरण', 'लार्वा चरण'),
('LARVAL', 'en', 'Larval stage', 'Larval stage'),
('EGG', 'mr', 'अंडी टप्पा', 'अंडी टप्पा'),
('EGG', 'hi', 'अंडा चरण', 'अंडा चरण'),
('EGG', 'en', 'Egg stage', 'Egg stage'),
('ADULT', 'mr', 'प्रौढ टप्पा', 'प्रौढ टप्पा'),
('ADULT', 'hi', 'वयस्क चरण', 'वयस्क चरण'),
('ADULT', 'en', 'Adult stage', 'Adult stage'),
('PUPAL', 'mr', 'कोष टप्पा', 'कोष टप्पा'),
('PUPAL', 'hi', 'प्यूपा चरण', 'प्यूपा चरण'),
('PUPAL', 'en', 'Pupal stage', 'Pupal stage'),
('NYMPH', 'mr', 'पिल्लू टप्पा', 'पिल्लू टप्पा'),
('NYMPH', 'hi', 'निम्फ चरण', 'निम्फ चरण'),
('NYMPH', 'en', 'Nymph stage', 'Nymph stage'),
-- Bee warning keys
('BEE_WARNING_HIGH', 'mr', 'फवारणी फक्त संध्याकाळी (5 वाजल्यानंतर) करा जेव्हा मधमाश्या निष्क्रिय असतात. फुलोरा असताना फवारणी करू नका.', 'मधमाशांसाठी अत्यंत विषारी'),
('BEE_WARNING_HIGH', 'hi', 'छिड़काव केवल शाम को (5 बजे के बाद) करें जब मधुमक्खियां निष्क्रिय हों। फूल आने पर छिड़काव न करें।', 'मधुमक्खियों के लिए अत्यधिक विषाक्त'),
('BEE_WARNING_HIGH', 'en', 'MANDATORY: Spray ONLY in evening hours (after 5 PM) when bees are inactive. Never spray during flowering.', 'High bee toxicity warning'),
('BEE_WARNING_MODERATE', 'mr', 'फुलोरा टाळून फवारणी करा. सकाळी लवकर किंवा संध्याकाळी उशीरा फवारणी करा.', 'मधमाशांसाठी मध्यम विषारी'),
('BEE_WARNING_MODERATE', 'hi', 'फूल आने के समय छिड़काव से बचें। सुबह जल्दी या शाम को देर से छिड़काव करें।', 'मधुमक्खियों के लिए मध्यम विषाक्त'),
('BEE_WARNING_MODERATE', 'en', 'Avoid spraying during flowering. Spray early morning or late evening.', 'Moderate bee toxicity warning'),
-- IPM/control types
('MECHANICAL_PHYSICAL_CONTROL', 'mr', 'यांत्रिक/भौतिक नियंत्रण', 'यांत्रिक किंवा भौतिक पद्धतीने नियंत्रण'),
('MECHANICAL_PHYSICAL_CONTROL', 'hi', 'यांत्रिक/भौतिक नियंत्रण', 'यांत्रिक या भौतिक तरीके से नियंत्रण'),
('MECHANICAL_PHYSICAL_CONTROL', 'en', 'Mechanical/Physical control', 'Mechanical or physical control method'),
('BIOLOGICAL_CONTROL', 'mr', 'जैविक नियंत्रण', 'जैविक पद्धतीने नियंत्रण'),
('BIOLOGICAL_CONTROL', 'hi', 'जैविक नियंत्रण', 'जैविक तरीके से नियंत्रण'),
('BIOLOGICAL_CONTROL', 'en', 'Biological control', 'Biological control method'),
('CHEMICAL_CONTROL', 'mr', 'रासायनिक नियंत्रण', 'रासायनिक पद्धतीने नियंत्रण (शेवटचा उपाय)'),
('CHEMICAL_CONTROL', 'hi', 'रासायनिक नियंत्रण', 'रासायनिक तरीके से नियंत्रण (अंतिम उपाय)'),
('CHEMICAL_CONTROL', 'en', 'Chemical control', 'Chemical control (last resort)'),
('CULTURAL_CONTROL', 'mr', 'सांस्कृतिक नियंत्रण', 'सांस्कृतिक पद्धतीने नियंत्रण'),
('CULTURAL_CONTROL', 'hi', 'सांस्कृतिक नियंत्रण', 'सांस्कृतिक तरीके से नियंत्रण'),
('CULTURAL_CONTROL', 'en', 'Cultural control', 'Cultural control method'),
-- Treatment types
('TREATMENT', 'mr', 'उपचार', 'उपचार करणे आवश्यक'),
('TREATMENT', 'hi', 'उपचार', 'उपचार आवश्यक'),
('TREATMENT', 'en', 'Treatment', 'Treatment required'),
('URGENT_ACTION', 'mr', 'तात्काळ कृती', 'तात्काळ कृती आवश्यक'),
('URGENT_ACTION', 'hi', 'तत्काल कार्रवाई', 'तत्काल कार्रवाई आवश्यक'),
('URGENT_ACTION', 'en', 'Urgent action', 'Urgent action required'),
('SEED_TREATMENT', 'mr', 'बीजप्रक्रिया', 'बियाणे प्रक्रिया'),
('SEED_TREATMENT', 'hi', 'बीज उपचार', 'बीज उपचार'),
('SEED_TREATMENT', 'en', 'Seed treatment', 'Seed treatment'),
('SOIL_DRENCH', 'mr', 'मातीत द्रावण', 'मातीत द्रावण ओतणे'),
('SOIL_DRENCH', 'hi', 'मिट्टी में डालें', 'मिट्टी में घोल डालना'),
('SOIL_DRENCH', 'en', 'Soil drench', 'Soil drench application'),
('FERTILIZER_APPLICATION', 'mr', 'खत वापर', 'खत वापरणे'),
('FERTILIZER_APPLICATION', 'hi', 'उर्वरक प्रयोग', 'उर्वरक प्रयोग'),
('FERTILIZER_APPLICATION', 'en', 'Fertilizer application', 'Fertilizer application')
ON CONFLICT (observation_code, language_code) DO UPDATE 
SET display_text = EXCLUDED.display_text, description_text = EXCLUDED.description_text;