-- ═══════════════════════════════════════════════════════════════════════════
-- ARCHITECTURAL CLEANUP: Remove language-specific response columns
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- These columns violate:
-- 1. Language independence principle
-- 2. SSOT: Narration must be handled by LLM layer, not stored in rules
-- 3. Scalability: Adding new languages should NOT require schema changes
--
-- Dependent views will be dropped and must be recreated as language-independent
-- ═══════════════════════════════════════════════════════════════════════════

-- First drop dependent views
DROP VIEW IF EXISTS public.decision_rules_en CASCADE;
DROP VIEW IF EXISTS public.v_decision_graph_nodes CASCADE;

-- Drop language-specific response columns
ALTER TABLE public.decision_rules DROP COLUMN IF EXISTS response_en;
ALTER TABLE public.decision_rules DROP COLUMN IF EXISTS response_hi;
ALTER TABLE public.decision_rules DROP COLUMN IF EXISTS response_mr;

-- Drop trigger_keywords which is a language-dependent heuristic field
ALTER TABLE public.decision_rules DROP COLUMN IF EXISTS trigger_keywords;

-- Drop action_text which duplicates narration responsibility  
ALTER TABLE public.decision_rules DROP COLUMN IF EXISTS action_text;

-- Add comment documenting the architectural decision
COMMENT ON TABLE public.decision_rules IS 'Symbolic decision rules. NO language-specific text. All narration is generated by LLM layer using i18n_keys and symbolic output.';

-- Create a language-independent decision rules view for admin use
CREATE OR REPLACE VIEW public.v_decision_rules_admin AS
SELECT 
  id,
  rule_id,
  crop_group,
  crop_code,
  category,
  stage_applicable,
  conditions_json,
  condition_code,
  cause,
  priority,
  action_type,
  canonical_group,
  is_active,
  version,
  scientific_source,
  scientific_basis,
  icar_package_ref,
  phi_days,
  active_ingredient,
  organic_alternative,
  ipm_level,
  bee_toxicity,
  created_at,
  updated_at
FROM public.decision_rules
WHERE is_active = true;