// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://qfklkkzxemsbeniyugiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma2xra3p4ZW1zYmVuaXl1Z2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjcxNjUsImV4cCI6MjA2ODAwMzE2NX0.dUnGp7wbwYom1FPbn_4EGf3PWjgmr8mXwL2w2SdYOh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {}
  }
});

// Header readiness tracking - Simple global state pattern (no circular dependencies)
let headersReady = false;
let headerPromise: Promise<void> | null = null;

// Store auth data globally to avoid circular imports
let globalAuthData: { userId: string; tenantId: string } | null = null;

// Server-verified session token (see supabase/functions/farmer-auth).
// This is the authoritative identity signal: the database resolves
// farmer_id / tenant_id from it and ignores the legacy headers when present.
const SESSION_TOKEN_STORAGE_KEY = 'ks_session_token';
let globalSessionToken: string | null =
  typeof localStorage !== 'undefined' ? localStorage.getItem(SESSION_TOKEN_STORAGE_KEY) : null;

export function getSessionToken(): string | null {
  return globalSessionToken;
}

export function setSessionToken(token: string | null) {
  globalSessionToken = token || null;
  try {
    if (token) localStorage.setItem(SESSION_TOKEN_STORAGE_KEY, token);
    else localStorage.removeItem(SESSION_TOKEN_STORAGE_KEY);
  } catch {
    /* storage unavailable (private mode) — in-memory token still works */
  }
  // Re-apply on the shared client and drop cached clients built without it.
  (supabase as any).rest.headers = {
    ...(supabase as any).rest.headers,
    ...(token ? { 'x-session-token': token } : {}),
  };
  if (!token) delete (supabase as any).rest.headers['x-session-token'];
  clientCache.clear();
}

// Client cache to prevent creating multiple GoTrueClient instances
const clientCache = new Map<string, ReturnType<typeof createClient<Database>>>();


/**
 * Set global auth data (called by auth store)
 * This breaks the circular dependency
 */
export function setGlobalAuthData(userId: string, tenantId: string) {
  globalAuthData = { userId, tenantId };
  headersReady = true;
}

/**
 * Clear global auth data (on logout)
 */
export function clearGlobalAuthData() {
  globalAuthData = null;
  setSessionToken(null);
  headersReady = false;
  headerPromise = null;
  // Clear client cache to prevent memory leaks
  clientCache.clear();
}

/**
 * Wait for Supabase headers to be set before making queries
 * This prevents race conditions where queries execute before auth headers are ready
 */
export function waitForHeaders(): Promise<void> {
  if (globalAuthData && headersReady) {
    return Promise.resolve();
  }
  if (headerPromise) {
    return headerPromise;
  }
  headerPromise = new Promise((resolve) => {
    let attempts = 0;
    const maxAttempts = 200; // 200 * 25ms = 5 seconds max
    const check = setInterval(() => {
      attempts++;
      if (globalAuthData && headersReady) {
        clearInterval(check);
        resolve();
      } else if (attempts >= maxAttempts) {
        clearInterval(check);
        console.error('❌ [Headers] Timeout after 5s - proceeding anyway');
        headersReady = true;
        resolve();
      }
    }, 25);
  });
  return headerPromise;
}

/**
 * Reset headers ready state (useful for testing or logout)
 */
export function resetHeadersState() {
  console.log('🔄 [Headers] Resetting state');
  clearGlobalAuthData();
}

/**
 * Update Supabase client headers with custom authentication context
 * This enables RLS policies to work with custom auth system
 */
export const updateSupabaseHeaders = (farmerId?: string, tenantId?: string) => {
  const headers: Record<string, string> = {};
  
  if (farmerId) {
    headers['x-farmer-id'] = farmerId;
  }
  
  if (tenantId) {
    headers['x-tenant-id'] = tenantId;
  }

  if (globalSessionToken) {
    headers['x-session-token'] = globalSessionToken;
  }
  
  // Update the global headers on the supabase client
  (supabase as any).rest.headers = {
    ...(supabase as any).rest.headers,
    ...headers
  };

  headersReady = true;
};

/**
 * Get Supabase client with auth headers automatically set
 * Always use this wrapper for authenticated requests
 * 
 * IMPORTANT: Uses cached clients to prevent "Multiple GoTrueClient instances" warning
 * Clients are cached per userId-tenantId combination for optimal performance
 */
export const supabaseWithAuth = (farmerId?: string, tenantId?: string) => {
  const userId = farmerId || globalAuthData?.userId;
  const tenant = tenantId || globalAuthData?.tenantId;
  
  // Strict validation: Check for missing OR empty string values
  if (!userId || !tenant || userId.trim() === '' || tenant.trim() === '') {
    console.warn('⚠️ [supabaseWithAuth] Invalid auth data:', { 
      userId: userId || '(empty)', 
      tenant: tenant || '(empty)',
      isEmptyString: userId === '' || tenant === ''
    });
    return supabase;
  }
  
  // Create cache key from userId, tenantId and session token
  const cacheKey = `${userId}-${tenant}-${globalSessionToken ?? 'anon'}`;
  
  // Return cached client if exists
  if (clientCache.has(cacheKey)) {
    return clientCache.get(cacheKey)!;
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false, // Don't persist, use custom auth
    },
    global: {
      headers: {
        'x-farmer-id': userId,
        'x-tenant-id': tenant,
        ...(globalSessionToken ? { 'x-session-token': globalSessionToken } : {}),
      }
    }
  });

  clientCache.set(cacheKey, client);
  return client;
};