// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfklkkzxemsbeniyugiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma2xra3p4ZW1zYmVuaXl1Z2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjcxNjUsImV4cCI6MjA2ODAwMzE2NX0.dUnGp7wbwYom1FPbn_4EGf3PWjgmr8mXwL2w2SdYOh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {}
  }
});

// Header readiness tracking
let headersReady = false;
let headersReadyPromise: Promise<void> | null = null;
let resolveHeadersReady: (() => void) | null = null;

/**
 * Wait for Supabase headers to be set before making queries
 * This prevents race conditions where queries execute before auth headers are ready
 */
export function waitForHeaders(): Promise<void> {
  if (headersReady) {
    console.log('🟢 [Headers] Already ready');
    return Promise.resolve();
  }
  
  if (headersReadyPromise) {
    console.log('⏳ [Headers] Waiting for existing promise');
    return headersReadyPromise;
  }
  
  console.log('🔄 [Headers] Creating wait promise');
  headersReadyPromise = new Promise((resolve) => {
    resolveHeadersReady = resolve;
    
    // Timeout after 3 seconds to prevent indefinite hanging
    setTimeout(() => {
      console.warn('⚠️ [Headers] Timeout after 3s, proceeding anyway');
      headersReady = true;
      resolve();
    }, 3000);
  });
  
  return headersReadyPromise;
}

/**
 * Reset headers ready state (useful for testing or logout)
 */
export function resetHeadersState() {
  headersReady = false;
  headersReadyPromise = null;
  resolveHeadersReady = null;
}

/**
 * Update Supabase client headers with custom authentication context
 * This enables RLS policies to work with custom auth system
 */
export const updateSupabaseHeaders = (farmerId?: string, tenantId?: string) => {
  const headers: Record<string, string> = {};
  
  if (farmerId) {
    headers['x-farmer-id'] = farmerId;
  }
  
  if (tenantId) {
    headers['x-tenant-id'] = tenantId;
  }
  
  // Update the global headers on the supabase client
  (supabase as any).rest.headers = {
    ...(supabase as any).rest.headers,
    ...headers
  };
  
  console.log('✅ [Headers] Updated Supabase headers:', headers);
  
  // Mark headers as ready and resolve any waiting promises
  headersReady = true;
  if (resolveHeadersReady) {
    resolveHeadersReady();
    resolveHeadersReady = null;
  }
};

/**
 * Get Supabase client with auth headers automatically set
 * Always use this wrapper for authenticated requests
 */
export const supabaseWithAuth = () => {
  // Import auth store dynamically to avoid circular dependencies
  const getAuthState = () => {
    try {
      const { useAuthStore } = require('@/stores/authStore');
      return useAuthStore.getState();
    } catch {
      return null;
    }
  };

  const authState = getAuthState();
  if (authState?.user?.id && authState?.user?.tenantId) {
    updateSupabaseHeaders(authState.user.id, authState.user.tenantId);
  }
  
  return supabase;
};