// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfklkkzxemsbeniyugiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma2xra3p4ZW1zYmVuaXl1Z2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjcxNjUsImV4cCI6MjA2ODAwMzE2NX0.dUnGp7wbwYom1FPbn_4EGf3PWjgmr8mXwL2w2SdYOh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {}
  }
});

// Header readiness tracking
let headersReady = false;
let headerPromise: Promise<void> | null = null;

/**
 * Wait for Supabase headers to be set before making queries
 * This prevents race conditions where queries execute before auth headers are ready
 * IMPROVED: Faster polling with immediate check
 */
export function waitForHeaders(): Promise<void> {
  // Immediate synchronous check first
  try {
    const { useAuthStore } = require('@/stores/authStore');
    const { user } = useAuthStore.getState();
    
    if (user?.id && user?.tenantId && headersReady) {
      console.log('🟢 [Headers] Already ready (immediate check)');
      return Promise.resolve();
    }
  } catch (error) {
    console.warn('⚠️ [Headers] Error in immediate check:', error);
  }
  
  if (headerPromise) {
    console.log('⏳ [Headers] Waiting for existing promise');
    return headerPromise;
  }
  
  console.log('🔄 [Headers] Creating wait promise with fast polling (25ms)');
  headerPromise = new Promise((resolve) => {
    let attempts = 0;
    const maxAttempts = 200; // 200 * 25ms = 5 seconds max
    
    // Actively poll auth store to check if user data is available
    const check = setInterval(() => {
      attempts++;
      
      try {
        // Dynamically import to avoid circular dependencies
        const { useAuthStore } = require('@/stores/authStore');
        const { user } = useAuthStore.getState();
        
        if (user?.id && user?.tenantId) {
          headersReady = true;
          clearInterval(check);
          console.log(`✅ [Headers] Ready via polling after ${attempts} attempts (${attempts * 25}ms) - user found:`, { 
            userId: user.id, 
            tenantId: user.tenantId 
          });
          resolve();
        }
        
        if (attempts >= maxAttempts) {
          clearInterval(check);
          console.error('❌ [Headers] Timeout after 5s - headers may not be ready!');
          headersReady = true; // Proceed anyway to prevent hanging
          resolve();
        }
      } catch (error) {
        console.warn('⚠️ [Headers] Error checking auth store:', error);
        if (attempts >= maxAttempts) {
          clearInterval(check);
          headersReady = true;
          resolve();
        }
      }
    }, 25); // Check every 25ms (faster than before)
  });
  
  return headerPromise;
}

/**
 * Reset headers ready state (useful for testing or logout)
 */
export function resetHeadersState() {
  console.log('🔄 [Headers] Resetting state');
  headersReady = false;
  headerPromise = null;
}

/**
 * Update Supabase client headers with custom authentication context
 * This enables RLS policies to work with custom auth system
 */
export const updateSupabaseHeaders = (farmerId?: string, tenantId?: string) => {
  const headers: Record<string, string> = {};
  
  if (farmerId) {
    headers['x-farmer-id'] = farmerId;
  }
  
  if (tenantId) {
    headers['x-tenant-id'] = tenantId;
  }
  
  // Update the global headers on the supabase client
  (supabase as any).rest.headers = {
    ...(supabase as any).rest.headers,
    ...headers
  };
  
  // Mark headers as ready
  headersReady = true;
  console.log('✅ [Headers] Set:', { farmerId, tenantId, headersReady });
};

/**
 * Get Supabase client with auth headers automatically set
 * Always use this wrapper for authenticated requests
 */
export const supabaseWithAuth = () => {
  // Import auth store dynamically to avoid circular dependencies
  const getAuthState = () => {
    try {
      const { useAuthStore } = require('@/stores/authStore');
      return useAuthStore.getState();
    } catch {
      return null;
    }
  };

  const authState = getAuthState();
  if (authState?.user?.id && authState?.user?.tenantId) {
    console.log('🔐 [supabaseWithAuth] Setting headers from current auth state');
    updateSupabaseHeaders(authState.user.id, authState.user.tenantId);
  } else {
    console.warn('⚠️ [supabaseWithAuth] No auth state available');
  }
  
  return supabase;
};