/**
 * ═══════════════════════════════════════════════════════════════════════════
 * BUNDLED AGRICULTURAL RULES - PLACEHOLDER
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * This file will be auto-generated by: scripts/bundle-rules.ts
 * 
 * For now, this is a placeholder that exports empty structures.
 * Run `npm run bundle-rules` to populate this file with actual rules.
 * 
 * Total expected rules: 2000+
 */

// ═══════════════════════════════════════════════════════════════════════════
// TYPE DEFINITIONS
// ═══════════════════════════════════════════════════════════════════════════

export interface BundledRule {
  rule_id: string;
  category: string;
  crop_code: string;
  stage_applicable: string[];
  conditionCode: string;
  cause: string;
  priority: number;
  scientific_source: string;
  scientific_basis: string;
  icar_package?: string;
  cause_confidence?: number;
  economic_tier?: string;
  estimated_cost_inr?: number;
  metadata?: {
    version?: string;
    author?: string;
    knowledge_layer?: string;
  };
  variety_filter?: {
    include?: string[];
    exclude?: string[];
  };
}

export interface BundleMetadata {
  totalRules: number;
  generatedAt: string;
  version: string;
  rulesByCategory: Record<string, number>;
  rulesByCropGroup: Record<string, number>;
}

// ═══════════════════════════════════════════════════════════════════════════
// PLACEHOLDER DATA - Will be replaced by bundler
// ═══════════════════════════════════════════════════════════════════════════

export const CROP_GROUP_RULES: Record<string, BundledRule[]> = {
  cereals: [],
  pulses: [],
  vegetables: [],
  fiber: [],
  oilseeds: [],
  fruits: [],
  spices: [],
  fodder: [],
  plantation: [],
  sugarcane: [],
  micronutrients: [],
  post_harvest: [],
};

export const SAFETY_RULES: Record<string, BundledRule[]> = {
  chemical_safety: [],
  emergency: [],
  phi_withdrawal: [],
  economic_threshold: [],
  ipm: [],
  crop_specific_ipm: [],
  resistance_management: [],
  harvest_quality: [],
  nutrient: [],
  water: [],
  weather_action: [],
  regional_seasonal: [],
  disease_management: [],
  soil_ph_interaction: [],
};

export const ADVANCED_RULES: BundledRule[] = [];

export const INTELLIGENCE_RULES: BundledRule[] = [];

export const BUNDLE_METADATA: BundleMetadata = {
  totalRules: 0,
  generatedAt: new Date().toISOString(),
  version: '0.0.0-placeholder',
  rulesByCategory: {},
  rulesByCropGroup: {},
};

// ═══════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════

export function getAllCropGroupRules(): BundledRule[] {
  return Object.values(CROP_GROUP_RULES).flat();
}

export function getAllSafetyRules(): BundledRule[] {
  return Object.values(SAFETY_RULES).flat();
}

export function getAllRules(): BundledRule[] {
  return [
    ...getAllCropGroupRules(),
    ...getAllSafetyRules(),
    ...ADVANCED_RULES,
    ...INTELLIGENCE_RULES,
  ];
}

export function getRuleCount(): number {
  return BUNDLE_METADATA.totalRules;
}
