/**
 * ═══════════════════════════════════════════════════════════════════════════
 * BUNDLED AGRICULTURAL RULES - AUTO-GENERATED
 * ═══════════════════════════════════════════════════════════════════════════
 * 
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Generated by: scripts/bundle-rules.ts
 * Generated at: 2026-01-06T19:13:54.147Z
 * Total rules: 0
 */

// ═══════════════════════════════════════════════════════════════════════════
// TYPE DEFINITIONS
// ═══════════════════════════════════════════════════════════════════════════

export interface BundledRule {
  rule_id: string;
  category: string;
  crop_code: string;
  stage_applicable: string[];
  conditionCode: string;
  cause: string;
  priority: number;
  scientific_source: string;
  scientific_basis: string;
  icar_package?: string;
  cause_confidence?: number;
  economic_tier?: string;
  estimated_cost_inr?: number;
  metadata?: {
    version?: string;
    author?: string;
    knowledge_layer?: string;
  };
  variety_filter?: {
    include?: string[];
    exclude?: string[];
  };
}

export interface BundleMetadata {
  totalRules: number;
  generatedAt: string;
  version: string;
  rulesByCategory: Record<string, number>;
  rulesByCropGroup: Record<string, number>;
}

// ═══════════════════════════════════════════════════════════════════════════
// BUNDLED RULES DATA
// ═══════════════════════════════════════════════════════════════════════════

export const CROP_GROUP_RULES: Record<string, BundledRule[]> = {};

export const SAFETY_RULES: Record<string, BundledRule[]> = {};

export const ADVANCED_RULES: BundledRule[] = [];

export const INTELLIGENCE_RULES: BundledRule[] = [];

export const BUNDLE_METADATA: BundleMetadata = {
  "totalRules": 0,
  "generatedAt": "2026-01-06T19:13:54.147Z",
  "version": "1.0.0",
  "rulesByCategory": {},
  "rulesByCropGroup": {}
};

// ═══════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════

export function getAllCropGroupRules(): BundledRule[] {
  return Object.values(CROP_GROUP_RULES).flat();
}

export function getAllSafetyRules(): BundledRule[] {
  return Object.values(SAFETY_RULES).flat();
}

export function getAllRules(): BundledRule[] {
  return [
    ...getAllCropGroupRules(),
    ...getAllSafetyRules(),
    ...ADVANCED_RULES,
    ...INTELLIGENCE_RULES,
  ];
}

export function getRuleCount(): number {
  return BUNDLE_METADATA.totalRules;
}
